/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EvaluationSetItemDeleteResponse {
    success: boolean;
    /** The ID of the deleted evaluation set item */
    evaluationSetItemId: string;
    /** Confirmation message */
    message: string;
}
