// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient";
import * as core from "../../../../core";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers";
import * as environments from "../../../../environments";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError";
import * as errors from "../../../../errors/index";
import * as Extend from "../../../index";

export declare namespace FormDetectionRunsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FormDetectionRunsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FormDetectionRunsClient.Options>;

    constructor(options: FormDetectionRunsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Start detecting fields in a PDF form and return immediately with a `form_detection_run` resource, typically in the `PROCESSING` state.
     *
     * Poll `GET /form_detection_runs/{id}` until the status is `PROCESSED` or `FAILED`. When processing succeeds, `output.schema` contains an edit schema you can pass directly to `POST /edit` or `POST /edit_runs`.
     *
     * @param {Extend.FormDetectionRunsCreateRequest} request
     * @param {FormDetectionRunsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Extend.BadRequestError}
     * @throws {@link Extend.UnauthorizedError}
     * @throws {@link Extend.PaymentRequiredError}
     * @throws {@link Extend.ForbiddenError}
     * @throws {@link Extend.NotFoundError}
     * @throws {@link Extend.UnprocessableEntityError}
     * @throws {@link Extend.TooManyRequestsError}
     * @throws {@link Extend.InternalServerError}
     *
     * @example
     *     await client.formDetectionRuns.create({
     *         file: {
     *             url: "https://example.com/form.pdf"
     *         },
     *         config: {
     *             instructions: "Detect the form fields and use human-readable field names.",
     *             advancedOptions: {
     *                 radioEnumsEnabled: true
     *             }
     *         }
     *     })
     */
    public create(
        request: Extend.FormDetectionRunsCreateRequest,
        requestOptions?: FormDetectionRunsClient.RequestOptions,
    ): core.HttpResponsePromise<Extend.FormDetectionRun> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Extend.FormDetectionRunsCreateRequest,
        requestOptions?: FormDetectionRunsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Extend.FormDetectionRun>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-extend-api-version": requestOptions?.extendApiVersion ?? "2026-02-09" }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ExtendEnvironment.Production,
                "form_detection_runs",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 300) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Extend.FormDetectionRun, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Extend.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Extend.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 402:
                    throw new Extend.PaymentRequiredError(
                        _response.error.body as Extend.ApiError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Extend.ForbiddenError(_response.error.body as Extend.ApiError, _response.rawResponse);
                case 404:
                    throw new Extend.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Extend.UnprocessableEntityError(
                        _response.error.body as Extend.ApiError,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Extend.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Extend.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ExtendError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/form_detection_runs");
    }

    /**
     * Retrieve the status and results of a form detection run.
     *
     * Use this endpoint to poll a run created with `POST /form_detection_runs`. When `status` is `PROCESSED`, `output.schema` contains the generated edit schema.
     *
     * @param {string} id - The unique identifier for the form detection run.
     *
     *                      Example: `"sgr_xK9mLPqRtN3vS8wF5hB2cQ"`
     * @param {Extend.FormDetectionRunsRetrieveRequest} request
     * @param {FormDetectionRunsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Extend.BadRequestError}
     * @throws {@link Extend.UnauthorizedError}
     * @throws {@link Extend.PaymentRequiredError}
     * @throws {@link Extend.ForbiddenError}
     * @throws {@link Extend.NotFoundError}
     * @throws {@link Extend.UnprocessableEntityError}
     * @throws {@link Extend.TooManyRequestsError}
     * @throws {@link Extend.InternalServerError}
     *
     * @example
     *     await client.formDetectionRuns.retrieve("sgr_xK9mLPqRtN3vS8wF5hB2cQ")
     */
    public retrieve(
        id: string,
        request: Extend.FormDetectionRunsRetrieveRequest = {},
        requestOptions?: FormDetectionRunsClient.RequestOptions,
    ): core.HttpResponsePromise<Extend.FormDetectionRun> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(id, request, requestOptions));
    }

    private async __retrieve(
        id: string,
        request: Extend.FormDetectionRunsRetrieveRequest = {},
        requestOptions?: FormDetectionRunsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Extend.FormDetectionRun>> {
        const { "x-extend-workspace-id": extendWorkspaceId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-extend-workspace-id": extendWorkspaceId,
                "x-extend-api-version": requestOptions?.extendApiVersion ?? "2026-02-09",
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ExtendEnvironment.Production,
                `form_detection_runs/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 300) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Extend.FormDetectionRun, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Extend.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Extend.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 402:
                    throw new Extend.PaymentRequiredError(
                        _response.error.body as Extend.ApiError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Extend.ForbiddenError(_response.error.body as Extend.ApiError, _response.rawResponse);
                case 404:
                    throw new Extend.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Extend.UnprocessableEntityError(
                        _response.error.body as Extend.ApiError,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Extend.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Extend.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ExtendError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/form_detection_runs/{id}");
    }
}
