// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         entityId: "entity_id_here",
 *         nextPageToken: "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="
 *     }
 */
export interface EvaluationSetsListRequest {
    /**
     * The ID of the extractor, classifier, or splitter to filter evaluation sets by.
     *
     * Example: `"ex_Xj8mK2pL9nR4vT7qY5wZ"`
     */
    entityId?: string;
    sortBy?: Extend.SortBy;
    sortDir?: Extend.SortDir;
    nextPageToken?: Extend.NextPageToken;
    maxPageSize?: Extend.MaxPageSize;
}
