/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         nextPageToken: "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="
 *     }
 */
export interface FileListRequest {
    /**
     * Filters files to only include those that contain the given string in the name.
     *
     * Example: `"invoice"`
     */
    nameContains?: string;
    /** Sorts the files in ascending or descending order. Ascending order means the earliest file is returned first. */
    sortDir?: Extend.SortDirEnum;
    nextPageToken?: Extend.NextPageToken;
    maxPageSize?: Extend.MaxPageSize;
}
