/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface PostFilesRequest {
    /** The name of the file */
    name?: string;
    /** A pre signed URL for the file */
    url?: string;
    /** The raw text content of the file */
    rawText?: string;
    /** The media type of the file (e.g. application/pdf) */
    mediaType?: string;
}
