/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the parser run:
 * * `"PROCESSED"` - The file was successfully processed
 * * `"FAILED"` - The processing failed (see failureReason for details)
 */
export type PostParseResponseStatus = "PROCESSED" | "FAILED";
export const PostParseResponseStatus = {
    Processed: "PROCESSED",
    Failed: "FAILED",
} as const;
