/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../index";

export interface PostParseResponseChunksItem {
    /** The type of object. Will be "chunk". */
    object: string;
    /** The type of chunk. */
    type: Extend.PostParseResponseChunksItemType;
    /** The parsed content of the chunk */
    content: string;
    /** Metadata about the chunk. */
    metadata: Extend.PostParseResponseChunksItemMetadata;
    /** An array of block objects that make up the chunk. See the [Block object](/developers/objects/block) documentation for more detailed information about block structure and types. */
    blocks: Extend.PostParseResponseChunksItemBlocksItem[];
}
