/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Extend from "../../../../api/index";
import * as core from "../../../../core";
import { EvaluationSetItem } from "../../../types/EvaluationSetItem";

export const PostEvaluationSetItemsResponse: core.serialization.ObjectSchema<
    serializers.PostEvaluationSetItemsResponse.Raw,
    Extend.PostEvaluationSetItemsResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    evaluationSetItem: EvaluationSetItem,
});

export declare namespace PostEvaluationSetItemsResponse {
    export interface Raw {
        success: boolean;
        evaluationSetItem: EvaluationSetItem.Raw;
    }
}
