// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         releaseType: "major"
 *     }
 */
export interface ClassifierVersionsCreateRequest {
    releaseType: Extend.ReleaseType;
    description?: Extend.VersionDescription;
    /** The configuration for this version of the classifier. */
    config?: Extend.ClassifyConfig;
}
