// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../index";

export interface SplittersListResponse {
    object?: "list";
    data?: Extend.SplitterSummary[];
    nextPageToken?: Extend.NextPageToken;
}
