/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../index";

export interface FileCreateResponse {
    success: boolean;
    file: Extend.File_;
}
