// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ProcessorUpdateRequest {
    /** The new name for the processor */
    name?: string;
    /**
     * The new configuration for the processor. The type of configuration must match the processor type:
     * * For classification processors, use `ClassificationConfig`
     * * For extraction processors, use `ExtractionConfig`
     * * For splitter processors, use `SplitterConfig`
     */
    config?: Extend.ProcessorUpdateRequestConfig;
}
