// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ProcessorListRequest {
    /** Filter processors by type */
    type?: Extend.LegacyProcessorType;
    /** Token for retrieving the next page of results */
    nextPageToken?: string;
    /** Maximum number of processors to return per page */
    maxPageSize?: number;
    /** Field to sort by */
    sortBy?: Extend.ProcessorListRequestSortBy;
    /** Sort direction */
    sortDir?: Extend.ProcessorListRequestSortDir;
}
