/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         type: "EXTRACT",
 *         nextPageToken: "nextPageToken",
 *         maxPageSize: 1,
 *         sortBy: "createdAt",
 *         sortDir: "asc"
 *     }
 */
export interface ProcessorListRequest {
    /** Filter processors by type */
    type?: Extend.LegacyProcessorType | null;
    /** Token for retrieving the next page of results */
    nextPageToken?: string | null;
    /** Maximum number of processors to return per page */
    maxPageSize?: number | null;
    /** Field to sort by */
    sortBy?: Extend.ProcessorListRequestSortBy | null;
    /** Sort direction */
    sortDir?: Extend.ProcessorListRequestSortDir | null;
}
