/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         name: "My Processor Name",
 *         type: "EXTRACT"
 *     }
 */
export interface ProcessorCreateRequest {
    /** The name of the new processor */
    name: string;
    type: Extend.ProcessorType;
    /**
     * The ID of an existing processor to clone. The ID will start with "dp_". One of `cloneProcessorId` or `config` must be provided.
     *
     * Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`
     */
    cloneProcessorId?: string;
    /** The configuration for the processor. The type of configuration must match the processor type. One of `cloneProcessorId` or `config` must be provided. */
    config?: Extend.ProcessorCreateRequestConfig;
    /** Whether to enable JSON schema for the processor. Defaults to false. */
    jsonSchemaEnabled?: boolean;
}
