// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         releaseType: "minor",
 *         description: "Updated extraction rules for better accuracy"
 *     }
 */
export interface ExtractorVersionsCreateRequest {
    releaseType: Extend.ReleaseType;
    description?: Extend.VersionDescription;
    /** The configuration for this version of the extractor. */
    config?: Extend.ExtractConfigJson;
}
