/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         file: {},
 *         config: {}
 *     }
 */
export interface PostParseRequest {
    /** A file object containing either a URL or a fileId. */
    file: Extend.PostParseRequestFile;
    config: Extend.ParseConfig;
}
