/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         responseType: "json"
 *     }
 */
export interface ParseRunsRetrieveRequest {
    /**
     * Controls how the output is delivered. Defaults to `inline`.
     * * `json` - Returns the output directly in the `output` field of the response body.
     * * `url` - Returns a presigned URL in the `outputUrl` field to download the output as a JSON file. The URL expires after 15 minutes. Useful for large outputs.
     */
    responseType?: Extend.ParseRunsRetrieveRequestResponseType | null;
}
