/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Extend from "../../../../api/index";
import * as core from "../../../../core";
import { ClassificationConfig } from "../../../types/ClassificationConfig";
import { ExtractionConfig } from "../../../types/ExtractionConfig";
import { SplitterConfig } from "../../../types/SplitterConfig";

export const ProcessorVersionCreateRequestConfig: core.serialization.Schema<
    serializers.ProcessorVersionCreateRequestConfig.Raw,
    Extend.ProcessorVersionCreateRequestConfig
> = core.serialization
    .union("type", {
        CLASSIFY: ClassificationConfig,
        EXTRACT: ExtractionConfig,
        SPLITTER: SplitterConfig,
    })
    .transform<Extend.ProcessorVersionCreateRequestConfig>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ProcessorVersionCreateRequestConfig {
    export type Raw =
        | ProcessorVersionCreateRequestConfig.Classify
        | ProcessorVersionCreateRequestConfig.Extract
        | ProcessorVersionCreateRequestConfig.Splitter;

    export interface Classify extends ClassificationConfig.Raw {
        type: "CLASSIFY";
    }

    export interface Extract extends ExtractionConfig.Raw {
        type: "EXTRACT";
    }

    export interface Splitter extends SplitterConfig.Raw {
        type: "SPLITTER";
    }
}
