/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         releaseType: "major"
 *     }
 */
export interface ProcessorVersionCreateRequest {
    /** The type of release for this version. The two options are "major" and "minor", which will increment the version number accordingly. */
    releaseType: Extend.ProcessorVersionCreateRequestReleaseType;
    /** A description of the changes in this version. This helps track the evolution of the processor over time. */
    description?: string;
    /** The configuration for this version of the processor. The type of configuration must match the processor type. */
    config?: Extend.ProcessorVersionCreateRequestConfig;
}
