/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export interface BadRequestErrorBody extends Extend.Error_ {
    code?: Extend.BadRequestErrorBodyCode;
}
