/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export interface BadRequestErrorBody {
    code?: Extend.BadRequestErrorBodyCode;
    success?: boolean;
    /** Error message */
    error?: string;
    /** Request ID for troubleshooting */
    requestId?: string;
    /** Whether the request can be retried */
    retryable?: boolean;
}
