// This file was auto-generated by Fern from our API Definition.

/** The type of chunk. */
export const ChunkType = {
    Page: "page",
    Document: "document",
    Section: "section",
} as const;
export type ChunkType = (typeof ChunkType)[keyof typeof ChunkType] | string;
