// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface Chunk {
    /** The type of object. In this case, it will always be `"chunk"`. */
    object: "chunk";
    /** The type of chunk. */
    type: Extend.ChunkType;
    /** The parsed content of the chunk. */
    content: string;
    /** Metadata about the chunk. */
    metadata: Extend.ChunkMetadata;
    /** An array of block objects that make up the chunk. A Block represents a distinct content element within a document, such as a paragraph of text, a heading, a table, or a figure. Blocks are the fundamental units that make up chunks in parsed documents. */
    blocks: Extend.Block[];
}
