/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The base processor to use. For classifiers, this must be either `"classifier_performance"` or `"classifier_light"`. See the [base processor documentation](https://docs.extend.ai/2025-04-21/changelog/overview) for more details.
 */
export type ClassificationConfigBaseProcessor = "classifier_performance" | "classifier_light";
export const ClassificationConfigBaseProcessor = {
    ClassifierPerformance: "classifier_performance",
    ClassifierLight: "classifier_light",
} as const;
