// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface ClassifierDraftUpdatedWebhookEvent {
    /** Unique identifier for the event */
    eventId: string;
    payload: Extend.Classifier;
}
