// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface Classifier {
    /** The type of object. Will always be `"classifier"`. */
    object: "classifier";
    /**
     * The ID of the classifier.
     *
     * Example: `"cl_Xj8mK2pL9nR4vT7qY5wZ"`
     */
    id: string;
    /**
     * The name of the classifier.
     *
     * Example: `"Document Type Classifier"`
     */
    name: string;
    createdAt: Extend.CreatedAt;
    updatedAt: Extend.UpdatedAt;
    /** The draft version of the classifier. This is the editable version in the Extend dashboard. */
    draftVersion: Extend.ClassifierVersion;
}
