/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export interface ClassifierOutput {
    /** The unique identifier for this classification */
    id: string;
    /** The type of classification */
    type: string;
    /** A value between 0 and 1 indicating the model's confidence in the classification, where 1 represents maximum confidence */
    confidence: number;
    /** Additional insights about the classification decision */
    insights: Extend.Insight[];
}
