/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * Summary representation of a classify run.
 */
export interface ClassifyRunSummary {
    /** The type of object. Will always be `"classify_run_summary"`. */
    object: "classify_run_summary";
    /** The unique identifier for this classify run. */
    id: string;
    /**
     * The classifier that was used for this run.
     *
     * **Availability:** Present when a classifier reference was provided. Not present when using inline `config`.
     */
    classifier: Extend.ClassifierSummary;
    /**
     * The version of the classifier that was used for this run.
     *
     * **Availability:** Present when a classifier reference was provided. Not present when using inline `config`.
     */
    classifierVersion: Extend.ClassifierVersionSummary;
    status: Extend.ProcessorRunStatus;
    /**
     * The reason for failure.
     *
     * **Availability:** Present when `status` is `"FAILED"`.
     */
    failureReason?: string;
    /**
     * A detailed message about the failure.
     *
     * **Availability:** Present when `status` is `"FAILED"`.
     */
    failureMessage?: string;
    /**
     * Any metadata that was provided when creating the classify run.
     *
     * **Availability:** Present when metadata was provided during creation.
     */
    metadata: Extend.RunMetadata;
    /** Indicates whether the run has been reviewed by a human. */
    reviewed: boolean;
    /** Indicates whether the run results have been edited during review. */
    edited: boolean;
    /** The file that was processed. */
    file: Extend.FileSummary;
    /**
     * The ID of the parse run that was used for this classify run.
     *
     * **Availability:** Present when a parse run was created.
     */
    parseRunId?: string;
    /** The URL to view the classify run in the Extend dashboard. */
    dashboardUrl: string;
    /**
     * Usage credits consumed by this run.
     *
     * **Availability:** This field will not be returned for:
     * * Runs created before October 7, 2025
     * * Customers on legacy billing systems
     */
    usage: Extend.RunUsage;
    createdAt: Extend.CreatedAt;
    updatedAt: Extend.UpdatedAt;
}
