// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface ConditionalStepDefinitionConfigConditionsItem {
    /** Unique ID for this condition branch. */
    id: string;
    type: Extend.ConditionalStepDefinitionConfigConditionsItemType;
    /**
     * The comparison operation for this branch.
     *
     * See the [Conditional step docs](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#conditional-step).
     */
    operation?: Extend.ConditionalStepDefinitionConfigConditionsItemOperation;
    /**
     * The left operand expression. This is typically a workflow variable or dynamic expression.
     *
     * See the [Conditional step docs](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#conditional-step).
     */
    leftOperand?: string;
    /**
     * The right operand value. This is typically a literal comparison value and is omitted for fallback branches like `ELSE`.
     *
     * See the [Conditional step docs](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#conditional-step).
     */
    rightOperand?: string;
}
