// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

/**
 * The result of a conditional extract step, which routes to different extractors based on rules.
 */
export interface ConditionalExtractResult {
    /** The extract run that was executed based on the matched rule. */
    extractRun: Extend.ExtractRun;
}
