// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface ConditionalExtractStepRunStep extends Extend.WorkflowStepBase {
    /** The type of workflow step. Will always be `"CONDITIONAL_EXTRACT"` for this step run type. */
    type?: "CONDITIONAL_EXTRACT";
}
