// This file was auto-generated by Fern from our API Definition.

/**
 * A next entry for `CONDITIONAL` steps. Routes based on which condition branch matched.
 *
 * See the [Configuring Workflows via API guide](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api) for end-to-end examples.
 */
export interface ConditionalNextEntry {
    /** The name of the target step. */
    step: string;
    /** Must match one of the `config.conditions[].id` values on the conditional step. */
    conditionId: string;
}
