// This file was auto-generated by Fern from our API Definition.

/**
 * Attribution for a resource created via the studio by a logged-in user.
 */
export interface CreatedByUser {
    /** The email address of the user who created the resource. */
    email: string;
}
