// This file was auto-generated by Fern from our API Definition.

/**
 * Attribution for a resource created via the API using an API key.
 */
export interface CreatedByApiKey {
    /** The name of the API key that created the resource. */
    name: string;
}
