/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Currency {
    /** The currency amount */
    amount: number;
    /** The ISO 4217 currency code (e.g. USD, EUR) */
    iso_4217_currency_code: string;
}
