// This file was auto-generated by Fern from our API Definition.

/**
 * Advanced options for schema generation.
 */
export interface EditSchemaGenerationConfigAdvancedOptions {
    /** Whether to parse table regions as arrays of objects. Defaults to `false`. */
    tableParsingEnabled?: boolean;
    /** Whether to model radio fields as enums. This ensures only one radio widget is selected. Defaults to `false`. */
    radioEnumsEnabled?: boolean;
    /** If enabled, only native AcroForm fields from the PDF will be imported and used in the schema, skipping object detection. Defaults to `false`. */
    nativeFieldsOnly?: boolean;
    /** When enabled, reads requirements explicitly stated in the form and adds supported root-level JSON Schema conditional validation rules to the generated schema. These rules validate form data when the schema is used for an edit; they do not add interactive UI behavior. If generated edit values do not satisfy the rules, the Edit run fails with `SCHEMA_VALIDATION_ERROR`. Defaults to `false`. */
    conditionalGenerationEnabled?: boolean;
}
