/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Advanced options for the edit operation.
 */
export interface EditRunConfigAdvancedOptions {
    /** Whether to flatten PDF forms before editing. */
    flattenPdf?: boolean;
    /** Whether to parse tables as arrays. */
    tableParsingEnabled?: boolean;
}
