// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

/**
 * Schema definition for an object field in a PDF edit schema. Used for signature fields and as items schema for arrays/tables.
 */
export interface EditObjectJson {
    /** Must be "object" for object schemas */
    type?: "object";
    /** Description of the field */
    description?: string;
    /** The PDF field type. For object schemas, must be "signature". */
    "extend_edit:field_type"?: "signature";
    /** Nested properties. Each property follows the EditJSON structure. */
    properties?: Record<string, Extend.EditJson>;
    /** List of required property names */
    required?: string[];
    /** Whether additional properties are allowed */
    additionalProperties?: boolean;
}
