// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

/**
 * Configuration options for edit schema generation.
 */
export interface EditSchemaGenerationConfig {
    /** The Edit engine version to use for form detection. Use an exact version for reproducible results, or `latest` to use the latest stable version. Defaults to `0.0.1` when omitted. Responses contain the resolved exact version. */
    engineVersion?: string;
    /**
     * Optional existing edit schema to map onto the detected form fields. When provided, the response may include a `mappingResult`
     * that shows which input schema paths matched the generated form fields.
     */
    inputSchema?: Extend.EditRootJson;
    /** Custom instructions provided for schema generation. */
    instructions?: string;
    /** Advanced options for schema generation. */
    advancedOptions?: Extend.EditSchemaGenerationConfigAdvancedOptions;
}
