/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Image fill for signature fields. Only PNG and JPEG image URLs are supported.
 */
export interface EditJsonSchemaExtendEditImage {
    /** URL of the image to place in the signature field. */
    image_url: string;
}
