// This file was auto-generated by Fern from our API Definition.

/**
 * Metrics about the editing process.
 *
 * **Availability:** Present when `status` is `"PROCESSED"`.
 */
export interface EditRunMetrics {
    /** Total processing time in milliseconds. */
    processingTimeMs: number;
    /** The number of pages in the document. */
    pageCount: number;
    /** The total number of fields in the schema. */
    fieldCount: number;
    /** The number of fields that were automatically detected. */
    fieldsDetectedCount: number;
    /** The number of fields that were annotated with bounding boxes. */
    fieldsAnnotatedCount: number;
    /** The time taken to detect fields in the document, in milliseconds. */
    fieldDetectionTimeMs: number;
    /** The time taken to annotate field positions in the document, in milliseconds. */
    fieldAnnotationTimeMs: number;
    /** The time taken to fill the fields in the document, in milliseconds. */
    fieldFillingTimeMs: number;
}
