// This file was auto-generated by Fern from our API Definition.

/**
 * A supported choice for a PDF form field.
 */
export interface EditSourceAcroFormOption {
    /** Value used in the Edit schema. */
    schemaValue: string;
    /** Value used by the PDF form field. */
    exportValue: string;
    /** Label shown in the PDF form. */
    displayValue: string;
}
