/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * Nested object/row schema used inside conditional array and object constraints.
 */
export interface EditConditionalObjectPropertySchema {
    /** Must be `object` for nested object conditional schemas. */
    type?: "object";
    /** Description of the nested object constraint. */
    description?: string;
    /** Nested conditional property constraints. */
    properties?: Record<string, Extend.EditConditionalPropertySchema>;
    /** Required nested properties. */
    required?: string[];
    /** Whether additional nested properties are allowed. */
    additionalProperties?: boolean;
}
