/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * The extractor, classifier, or splitter that was run.
 */
export type EvaluationSetRunEntity =
    | Extend.EvaluationSetRunEntity.ExtractorSummary
    | Extend.EvaluationSetRunEntity.ClassifierSummary
    | Extend.EvaluationSetRunEntity.SplitterSummary;

export namespace EvaluationSetRunEntity {
    export interface ExtractorSummary extends Extend.ExtractorSummary {
        object: "extractor_summary";
    }

    export interface ClassifierSummary extends Extend.ClassifierSummary {
        object: "classifier_summary";
    }

    export interface SplitterSummary extends Extend.SplitterSummary {
        object: "splitter_summary";
    }
}
