// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface EvaluationSetItem {
    /** The type of object. In this case, it will always be `"evaluation_set_item"`. */
    object: "evaluation_set_item";
    /**
     * The ID of the evaluation set item.
     *
     * Example: `"evi_kR9mNP12Qw4yTv8BdR3H"`
     */
    id: string;
    /**
     * The ID of the evaluation set that this item belongs to.
     *
     * Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`
     */
    evaluationSetId: string;
    /** A summary of the file associated with the evaluation set item. */
    file: Extend.FileSummary;
    /** The expected output that will be used to evaluate the performance of the extractor, classifier, or splitter associated with the evaluation set. This must conform to the output schema of the entity associated with the evaluation set. */
    expectedOutput: Extend.ProvidedProcessorOutput;
}
