// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface ExternalDataValidationStepRun extends Extend.StepRunBase {
    step: Extend.ExternalDataValidationStepRunStep;
    /** The result of this external data validation step. Currently, `result` is always present for returned step runs. It is nullable to allow for future support of returning step runs with non-successful statuses. */
    result: Extend.ExternalDataValidationResult | null;
}
