// This file was auto-generated by Fern from our API Definition.

/**
 * Whether to continue or exit the workflow on validation failure. Defaults to `CONTINUE`.
 *
 * See the [External Data Validation step docs](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#external-data-validation-step).
 */
export const ExternalDataValidationStepDefinitionConfigFailureBehavior = {
    Continue: "CONTINUE",
    Exit: "EXIT",
} as const;
export type ExternalDataValidationStepDefinitionConfigFailureBehavior =
    | (typeof ExternalDataValidationStepDefinitionConfigFailureBehavior)[keyof typeof ExternalDataValidationStepDefinitionConfigFailureBehavior]
    | string;
