/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExtractionJsonSchemaOutputMetadataValueCitationsItemPolygonItem {
    /** X coordinate of the point */
    x: number;
    /** Y coordinate of the point */
    y: number;
}
