// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface ExtractStepRun extends Extend.StepRunBase {
    step: Extend.ExtractStepRunStep;
    /** The extract run that was executed. Will be null if the extract step was not successful. */
    result: Extend.ExtractRun | null;
}
