/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A record of edits made to the processor output.
 */
export interface ExtractionOutputEdits {
    /** The original value before editing. */
    originalValue?: unknown;
    /** The value after editing. */
    editedValue?: unknown;
    /** Any notes added during editing. */
    notes?: string;
    /** The page number where the edit was made. */
    page?: number;
    /** The type of the edited field. */
    fieldType?: string;
}
