// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface ExtractAdvancedOptions {
    /** Whether to enable model reasoning insights. */
    modelReasoningInsightsEnabled?: boolean;
    /** Whether to enable advanced multimodal features. */
    advancedMultimodalEnabled?: boolean;
    /** Whether to enable citations in the output. */
    citationsEnabled?: boolean;
    /**
     * Controls the granularity of citations returned alongside extracted values. Requires `citationsEnabled=true` and a base processor version that supports bounding box citations.
     * - `line`: Use OCR lines for citations. This can return one or more relevant OCR lines for each citation. This is the default mode.
     * - `word`: Narrow each matched citation down to the relevant OCR word span when possible. Note: this might still return line citations in cases where the citation model is unable to reliably narrow down to a word-level citation. Typically, this only makes sense when you are doing array extraction and want precise word citations from a given cell in a table to match an array property, e.g. `line_items.total`.
     * - `block`: Use parser blocks (e.g. full paragraphs, key-val regions, tables, lists, etc.) and return block-level polygons for each citation. Will have highest recall in terms of overlap with the extracted value source, but least granularity.
     */
    citationMode?: Extend.ExtractAdvancedOptionsCitationMode;
    /**
     * Granularity for array citations. Requires turning on citations: `citationsEnabled=true`.
     * - `item`: Creates item-level citations for array fields. This will return a single bbox citation for each "item" in the array e.g. line_items[0], line_items[1], etc.
     * - `property`: Creates property-level citations (cell-level citations) for array fields. This will return a citation for each property/cell for every item/row in the array, e.g. line_items[0].description, line_items[1].price, etc.
     */
    arrayCitationStrategy?: Extend.ExtractAdvancedOptionsArrayCitationStrategy;
    /** Strategy for handling large arrays in documents. */
    arrayStrategy?: Extend.ArrayStrategy;
    chunkingOptions?: Extend.ExtractChunkingOptions;
    /** Ranges of sheet indices to extract from Excel documents. */
    excelSheetRanges?: Extend.ExcelSheetRange[];
    /** Strategy for selecting sheets from Excel documents. */
    excelSheetSelectionStrategy?: Extend.ExtractAdvancedOptionsExcelSheetSelectionStrategy;
    pageRanges?: Extend.PageRanges;
    /**
     * Configuration for the review agent that analyzes extraction results.
     * When enabled, each field in the output metadata will include a `reviewAgentScore` (1-5)
     * and may include additional `insights` of type `issue` or `review_summary` to help identify
     * fields that may need manual review.
     *
     * Enabling the review agent incurs additional credits.
     *
     * To learn more, view the [Review Agent Documentation](https://docs.extend.ai/2026-02-09/extraction/review-agent)
     */
    reviewAgent?: Extend.ExtractAdvancedOptionsReviewAgent;
    /** Whether to include the current date as context for the model during extraction. Defaults to `false`. */
    currentDateEnabled?: boolean;
}
