// This file was auto-generated by Fern from our API Definition.

/** Strategy for selecting sheets from Excel documents. */
export const ExtractAdvancedOptionsExcelSheetSelectionStrategy = {
    Intelligent: "intelligent",
    All: "all",
    First: "first",
    Last: "last",
} as const;
export type ExtractAdvancedOptionsExcelSheetSelectionStrategy =
    | (typeof ExtractAdvancedOptionsExcelSheetSelectionStrategy)[keyof typeof ExtractAdvancedOptionsExcelSheetSelectionStrategy]
    | string;
