// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

/**
 * Metrics for an evaluation set run against an extractor.
 */
export interface ExtractEvaluationSetRunMetrics extends Extend.EvaluationSetRunMetricsBase {
    /** Aggregate accuracy across every reviewed field in `fieldMetrics`. */
    accuracy?: number;
    /** Per-field accuracy statistics. Keys are the extractor schema's field names — nested fields are flattened to dot-joined paths. See [Extraction response format](https://docs.extend.ai/2026-02-09/extraction/response-format#output-value-and-metadata) for more on how extractor field paths are structured. */
    fieldMetrics?: Record<string, Extend.EvaluationSetRunFieldMetric>;
}
