// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface Extractor {
    /** The type of object. Will always be `"extractor"`. */
    object: "extractor";
    /**
     * The ID of the extractor.
     *
     * Example: `"ex_Xj8mK2pL9nR4vT7qY5wZ"`
     */
    id: string;
    /**
     * The name of the extractor.
     *
     * Example: `"Invoice Extractor"`
     */
    name: string;
    createdAt: Extend.CreatedAt;
    updatedAt: Extend.UpdatedAt;
    /** The draft version of the extractor. This is the editable version in the Extend dashboard. */
    draftVersion: Extend.ExtractorVersion;
}
