/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * Details for figure blocks
 */
export interface FigureDetails {
    /** Indicates this is a figure details object */
    type: "figure_details";
    /** URL to the clipped/segmented figure image. Only set if the option `figureImageClippingEnabled` in the input is `true`, which it is by default. */
    imageUrl?: string;
    /**
     * The refined type of figure - only set when figure classification and summarization is enabled. Possible values:
     *
     * * `image`: A photographic image
     * * `chart`: A data chart or graph
     * * `diagram`: A schematic or diagram
     * * `logo`: A company or brand logo
     * * `other`: Any other type of figure
     */
    figureType?: Extend.FigureDetailsFigureType;
}
