// This file was auto-generated by Fern from our API Definition.

/** The type of the file based on the file extension or content type. */
export const FileType = {
    Pdf: "PDF",
    Csv: "CSV",
    Img: "IMG",
    Txt: "TXT",
    Docx: "DOCX",
    Excel: "EXCEL",
    Xml: "XML",
    Html: "HTML",
} as const;
export type FileType = (typeof FileType)[keyof typeof FileType] | string;
