// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface FileConversionStepDefinitionConfig {
    /**
     * Whether to continue or exit the workflow if file conversion fails. Defaults to `EXIT`.
     *
     * See the [File Conversion step docs](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#file-conversion-step).
     */
    failureBehavior?: Extend.FileConversionStepDefinitionConfigFailureBehavior;
}
