/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export interface FileContents {
    /** The raw text content of the file. This is included for all file types if the `rawText` query parameter is set to true in the endpoint request. */
    rawText?: string;
    /** Cleaned and structured markdown content of the entire file. Available for PDF and IMG file types. Only included if the `markdown` query parameter is set to true in the endpoint request. */
    markdown?: string;
    pages?: Extend.FileContentsPagesItem[];
    sheets?: Extend.FileContentsSheetsItem[];
}
