/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export interface FileSummary {
    /** The type of object. Will always be `"file_summary"`. */
    object: "file_summary";
    /**
     * ID for the file.
     *
     * Example: `"file_xK9mLPqRtN3vS8wF5hB2cQ"`
     */
    id: string;
    /**
     * The name of the file
     *
     * Example: `"Invoices.pdf"`
     */
    name: string;
    /**
     * The type of the file.
     *
     * **Availability:** Present when the file type could be determined.
     */
    type?: Extend.FileType;
    /**
     * ID of the parent file.
     *
     * **Availability:** Present for files created via a Splitter in a workflow.
     */
    parentFileId?: string;
    metadata: Extend.FileMetadata;
    createdAt: Extend.CreatedAt;
    updatedAt: Extend.UpdatedAt;
}
