// This file was auto-generated by Fern from our API Definition.

/**
 * Raw text data to be processed. This will be used to create a `.txt` file.
 */
export interface FileFromText {
    /** A string containing raw text data to be processed. */
    text: string;
    /** The name of the created text file. If not set, the file name is generated. */
    name?: string;
}
