// This file was auto-generated by Fern from our API Definition.

/**
 * Whether to continue or exit the workflow if file conversion fails. Defaults to `EXIT`.
 *
 * See the [File Conversion step docs](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#file-conversion-step).
 */
export const FileConversionStepDefinitionConfigFailureBehavior = {
    Continue: "CONTINUE",
    Exit: "EXIT",
} as const;
export type FileConversionStepDefinitionConfigFailureBehavior =
    | (typeof FileConversionStepDefinitionConfigFailureBehavior)[keyof typeof FileConversionStepDefinitionConfigFailureBehavior]
    | string;
