// This file was auto-generated by Fern from our API Definition.

/**
 * The status of the form detection run:
 * * `"PROCESSING"` - The form is still being analyzed
 * * `"PROCESSED"` - Form detection completed successfully
 * * `"FAILED"` - Form detection failed (see `failureReason` for details)
 */
export const FormDetectionRunStatus = {
    Processing: "PROCESSING",
    Processed: "PROCESSED",
    Failed: "FAILED",
} as const;
export type FormDetectionRunStatus = (typeof FormDetectionRunStatus)[keyof typeof FormDetectionRunStatus] | string;
