/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export interface JsonSchema {
    /** The extracted values conforming to the schema defined in the processor config */
    value: Record<string, unknown>;
    /** Metadata about the extracted fields */
    metadata: Record<string, Extend.JsonSchemaMetadataValue>;
}
