/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of processor:
 * * `"CLASSIFY"` - Classifies documents into categories
 * * `"EXTRACT"` - Extracts structured data from documents
 * * `"SPLITTER"` - Splits documents into multiple parts
 */
export type LegacyProcessorRunType = "CLASSIFY" | "EXTRACT" | "SPLITTER";
export const LegacyProcessorRunType = {
    Classify: "CLASSIFY",
    Extract: "EXTRACT",
    Splitter: "SPLITTER",
} as const;
