// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface LegacyListProcessorsProcessor {
    /** The type of response. In this case, it will always be `"document_processor"`. */
    object: "document_processor";
    /**
     * The ID of the processor.
     *
     * Example: `"ex_Xj8mK2pL9nR4vT7qY5wZ"`
     */
    id: string;
    /**
     * The name of the processor.
     *
     * Example: `"Invoice Processor"`
     */
    name: string;
    type: Extend.LegacyProcessorType;
    /** Array of all versions for this processor */
    versions: Extend.LegacyListProcessorsProcessorVersion[];
    /**
     * The time (in UTC) at which the processor was created. Will follow the RFC 3339 format.
     *
     * Example: `"2024-03-21T15:30:00Z"`
     */
    createdAt: string;
    /**
     * The time (in UTC) at which the processor was last updated. Will follow the RFC 3339 format.
     *
     * Example: `"2024-03-21T16:45:00Z"`
     */
    updatedAt: string;
}
