// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface LegacyProcessorRunSummary {
    /**
     * The ID of the processor run.
     *
     * Example: `"exr_Zk9mNP12Qw4-yTv8BdR3H"`
     */
    id: string;
    status: Extend.LegacyProcessorStatus;
    /**
     * The ID of the processor that was run. Will always start with "ex_".
     *
     * Example: `"ex_BMdfq_yWM3sT-ZzvCnA3f"`
     */
    processorId: string;
    /**
     * The name of the processor that was run.
     *
     * Example: `"Invoice Extractor"`
     */
    processorName: string;
    /**
     * The ID of the processor version that was run. Will always start with "exv_".
     *
     * Example: `"exv_Zk9mNP12Qw4-yTv8BdR3H"`
     */
    processorVersionId: string;
    /**
     * The type of processor that was run:
     * * `"EXTRACT"` - Extraction processor
     * * `"SPLITTER"` - Splitting processor
     * * `"CLASSIFY"` - Classification processor
     */
    type?: Extend.LegacyProcessorRunSummaryType;
    /**
     * The time (in UTC) at which the processor run was created. Will follow the RFC 3339 format.
     *
     * Example: `"2024-03-21T15:29:55Z"`
     */
    createdAt: string;
    /**
     * The time (in UTC) at which the processor run was last updated. Will follow the RFC 3339 format.
     *
     * Example: `"2024-03-21T16:45:00Z"`
     */
    updatedAt: string;
    usage?: Extend.LegacyDocumentProcessorRunCredits;
}
