// This file was auto-generated by Fern from our API Definition.

export interface LegacyListProcessorsProcessorVersion {
    /**
     * The unique identifier for this version of the document processor.
     *
     * Example: `"exv_xK9mLPqRtN3vS8wF5hB2cQ"`
     */
    id: string;
    /**
     * The version number or identifier for this processor version.
     *
     * Example: `"3"`
     */
    version: string;
}
