// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

/**
 * A mapping of field names to their extracted values
 */
export type LegacyProvidedFieldsArrayOutput = Record<string, Extend.LegacyProvidedExtractionFieldResult>;
