// This file was auto-generated by Fern from our API Definition.

export interface LegacyBatchProcessorRunMetrics {
    /** The total number of files processed in this batch run */
    numFiles?: number;
    /** The total number of pages processed in this batch run */
    numPages?: number;
}
