// This file was auto-generated by Fern from our API Definition.

/** The base processor to use. For classifiers, this must be either `"classification_performance"` or `"classification_light"`. See [Classification Changelog](/changelog/classification/classification-performance) for more details. */
export const LegacyClassificationConfigBaseProcessor = {
    ClassificationPerformance: "classification_performance",
    ClassificationLight: "classification_light",
} as const;
export type LegacyClassificationConfigBaseProcessor =
    | (typeof LegacyClassificationConfigBaseProcessor)[keyof typeof LegacyClassificationConfigBaseProcessor]
    | string;
