// This file was auto-generated by Fern from our API Definition.

/** The type of the extraction field result */
export const LegacyProvidedExtractionFieldResultType = {
    String: "string",
    Number: "number",
    Currency: "currency",
    Boolean: "boolean",
    Date: "date",
    Array: "array",
    Enum: "enum",
    Object: "object",
    Signature: "signature",
} as const;
export type LegacyProvidedExtractionFieldResultType =
    | (typeof LegacyProvidedExtractionFieldResultType)[keyof typeof LegacyProvidedExtractionFieldResultType]
    | string;
