// This file was auto-generated by Fern from our API Definition.

/**
 * These are usage credits for document processing (extraction, classification, or splitting). File parsing credits are tracked separately and can be retrieved from the [Get File](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/file/get-file) endpoint.
 *
 * This field will not be returned for processor runs created before October 7, 2025, or for customers on legacy billing systems.
 *
 * For more details on how credits work, see our [Credits Guide](https://docs.extend.ai/2026-02-09/product/general/how-credits-work).
 */
export interface LegacyDocumentProcessorRunCredits {
    /** The number of credits consumed specifically for document processing in this processor run. This does not include file parsing credits. */
    credits: number;
}
