// This file was auto-generated by Fern from our API Definition.

/**
 * The source of the batch processor run:
 * * `"EVAL_SET"` - The batch processor run was made from an evaluation set. The `sourceId` will be the ID of the evaluation set (e.g., `"ev_1234"`)
 * * `"PLAYGROUND"` - The batch processor run was made from the playground. The `sourceId` will not be set
 * * `"STUDIO"` - The batch processor run was made for a processor in Studio. The `sourceId` will be the ID of the processor (e.g., `"ex_1234"`)
 */
export const LegacyBatchProcessorRunSource = {
    EvalSet: "EVAL_SET",
    Playground: "PLAYGROUND",
    Studio: "STUDIO",
} as const;
export type LegacyBatchProcessorRunSource =
    | (typeof LegacyBatchProcessorRunSource)[keyof typeof LegacyBatchProcessorRunSource]
    | string;
