// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

/**
 * The output from an extraction processor
 */
export type LegacyFieldsArrayOutput = Record<string, Extend.LegacyExtractionFieldResult>;
