/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * Limit processing to the specified page ranges. See [Page Ranges](https://docs.extend.ai/2025-04-21/product/page-ranges).
 */
export type PageRanges = Extend.PageRangesItem[];
