// This file was auto-generated by Fern from our API Definition.

export interface PageRangesItem {
    /** The start page of the range. */
    start: number;
    /** The end page of the range. */
    end: number;
}
