// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface ParseStepRun extends Extend.StepRunBase {
    step: Extend.ParseStepRunStep;
    /** The parse run that was executed. Will be null if the parse step was not successful. */
    result: Extend.ParseRun | null;
}
