// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export interface ParseConfigAdvancedOptions {
    /** Whether to automatically detect and correct page rotation. */
    pageRotationEnabled?: boolean;
    pageRanges?: Extend.PageRanges;
    /**
     * Controls how Excel files are parsed.
     *
     * * `basic`: Fast, deterministic parsing.
     * * `advanced`: Enable layout block detection for complex spreadsheets.
     *
     * For `.xls` files, `basic` mode is always used.
     */
    excelParsingMode?: Extend.ParseConfigAdvancedOptionsExcelParsingMode;
    /** Whether to exclude hidden rows, columns, and sheets when parsing Excel files. */
    excelSkipHiddenContent?: boolean;
    /** Whether to return raw calculated cell values instead of locale-formatted values when parsing Excel files. Useful when downstream processing needs the underlying numeric or unformatted data. */
    excelUseRawCellValues?: boolean;
    /** Whether to skip formula recalculation when opening Excel workbooks. Significantly improves parsing speed for formula-heavy spreadsheets. Disable if cell values depend on volatile functions like NOW() or TODAY(). */
    excelSkipCalculation?: boolean;
    /** Multiplier for the Y-axis threshold used to determine if text blocks should be placed on the same line or not (0.1-5.0, default 1.0). Higher values group elements that are further apart vertically. Only applies when the spatial target is set. */
    verticalGroupingThreshold?: number;
    /** Options for returning raw OCR data in the response. */
    returnOcr?: Extend.ParseConfigAdvancedOptionsReturnOcr;
    /** Whether to convert supported file types (images, Word documents, PowerPoint, Excel, HTML) to PDF before parsing. This can improve parsing quality for some file types and ensures spatial output with bounding boxes. */
    alwaysConvertToPdf?: boolean;
    /**
     * The format used for enrichment annotations in the output.
     *
     * * `xml`: Use XML-style tags for enrichment annotations, e.g. <page_number>1</page_number> or <barcode>1234567890</barcode>
     * * `bracket`: Use bracket-style notation for enrichment annotations, e.g. [page_number: 1] or [barcode: 1234567890]
     */
    enrichmentFormat?: Extend.ParseConfigAdvancedOptionsEnrichmentFormat;
    /**
     * Controls the quality level when converting images or documents to PDF for parsing.
     *
     * * `high`: Maximum quality, can add some latency for large/dense documents
     * * `medium`: Balanced quality and speed
     * * `low`: Lower quality, smaller file sizes, faster processing
     */
    imageConversionQuality?: Extend.ParseConfigAdvancedOptionsImageConversionQuality;
    /**
     * Enable detection of formatting-based annotations in the document. Currently supports change tracking detection.
     *
     * When enabled, detected changes are represented inline within the `content` field of applicable blocks using standard HTML change-tracking elements: [`<ins>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ins) for insertions and [`<del>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del) for deletions, grouped inside a `<change>` wrapper.
     *
     * Affected block types: `text`, `heading`, `section_heading`, `header`, `footer`.
     *
     * **Note:** Requires `engine: "parse_performance"` with `engineVersion >= "2.0.0"`.
     */
    formattingDetection?: Extend.ParseConfigAdvancedOptionsFormattingDetectionItem[];
}
