// This file was auto-generated by Fern from our API Definition.

/**
 * Options for barcode blocks.
 */
export interface ParseConfigBlockOptionsBarcodes {
    /** Whether to clip and extract images of barcodes. When enabled, barcode images will be available in the `imageUrl` field of BarcodeDetails. */
    imageClippingEnabled?: boolean;
    /** Whether to decode and read barcode values. When enabled, decoded values will be available in the `decodedValue` field of BarcodeDetails. */
    readingEnabled?: boolean;
}
