// This file was auto-generated by Fern from our API Definition.

/**
 * Controls how Excel files are parsed.
 *
 * * `basic`: Fast, deterministic parsing.
 * * `advanced`: Enable layout block detection for complex spreadsheets.
 *
 * For `.xls` files, `basic` mode is always used.
 */
export const ParseConfigAdvancedOptionsExcelParsingMode = {
    Basic: "basic",
    Advanced: "advanced",
} as const;
export type ParseConfigAdvancedOptionsExcelParsingMode =
    | (typeof ParseConfigAdvancedOptionsExcelParsingMode)[keyof typeof ParseConfigAdvancedOptionsExcelParsingMode]
    | string;
