// This file was auto-generated by Fern from our API Definition.

/**
 * Options for agentic table processing using VLM-based review and correction. Enabling this incurs additional credits on pages where agentic table correction is triggered.
 */
export interface ParseConfigBlockOptionsTablesAgentic {
    /** Whether to enable agentic table processing. */
    enabled?: boolean;
    /** Custom instructions to guide the agentic table processing. */
    customInstructions?: string;
}
