/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the parse run:
 * * `"PROCESSING"` - The file is still being processed
 * * `"PROCESSED"` - The file was successfully processed
 * * `"FAILED"` - The processing failed (see `failureReason` for details)
 */
export type ParseRunStatusStatus = "PROCESSING" | "PROCESSED" | "FAILED";
export const ParseRunStatusStatus = {
    Processing: "PROCESSING",
    Processed: "PROCESSED",
    Failed: "FAILED",
} as const;
