// This file was auto-generated by Fern from our API Definition.

export interface ParseRunOutputMetadataPagesItem {
    /** The page number this entry describes. */
    number: number;
    /** Degrees Extend rotated the page clockwise to make it upright. `0` if rotation detection ran and the page was already upright; `null` if rotation detection was disabled for this run. */
    rotationApplied: number | null;
    /** The file's true page width, independent of rendering resolution. */
    originalPageWidth: number;
    /** The file's true page height, independent of rendering resolution. */
    originalPageHeight: number;
    /** The DPI that `boundingBox`/`polygon` coordinates on this page are scaled to. Multiply `originalPageWidth`/`originalPageHeight` by `dpi / 72` to convert them into that same coordinate space. */
    dpi: number;
}
