// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

/**
 * The parse run output.
 *
 * **Availability:** Present when `status` is `"PROCESSED"` and the request was made without the `responseType=url` query parameter. Contains the parsed chunks.
 */
export interface ParseRunOutput {
    /** An array of chunks that were parsed from the file. */
    chunks: Extend.Chunk[];
    /** Raw OCR data from the parsing process. Only included when `returnOcr` is configured in the parse config's advanced options. */
    ocr?: Extend.ParseRunOutputOcr;
    /** Rotation, dimension, and file-type metadata about the parse output. `null` for parse runs that completed before this field was introduced. */
    metadata?: Extend.ParseRunOutputMetadata | null;
}
