/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The bounding box coordinates of the word.
 */
export interface ParserRunOcrWordsItemBoundingBox {
    /** The left coordinate of the bounding box. */
    left: number;
    /** The right coordinate of the bounding box. */
    right: number;
    /** The top coordinate of the bounding box. */
    top: number;
    /** The bottom coordinate of the bounding box. */
    bottom: number;
}
