/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * Options for table blocks.
 */
export interface ParseConfigBlockOptionsTables {
    /** Whether to include tables in the output. */
    enabled?: boolean;
    /**
     * The target format for the table blocks. Supported values:
     * * `markdown`: Convert table to Markdown format
     * * `html`: Convert table to HTML format
     */
    targetFormat?: Extend.ParseConfigBlockOptionsTablesTargetFormat;
    /** Whether to automatically copy table headers to headerless tables on subsequent pages when they have matching column counts. Useful for multi-page tables. */
    tableHeaderContinuationEnabled?: boolean;
}
