// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

export type ProvidedProcessorOutput =
    | Extend.ProvidedExtractOutput
    | Extend.ProvidedClassifyOutput
    | Extend.ProvidedSplitOutput;
