// This file was auto-generated by Fern from our API Definition.

export interface ProvidedClassifyOutput {
    /** The unique identifier for this classification (defined in the classifier config) */
    id: string;
    /** The type of classification (defined in the classifier config) */
    type: string;
}
