/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export interface ProvidedExtractionFieldResult {
    /** The unique identifier for this field */
    id: string;
    value?: unknown;
    /** The type of the extraction field result */
    type?: Extend.ProvidedExtractionFieldResultType;
    /** A value between 0 and 1 indicating confidence in the extraction. Will be set to 1 if not provided. */
    confidence?: number;
    /** The page number where this field was extracted from */
    page?: number;
}
