/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export type ProvidedProcessorOutput =
    | Extend.ProvidedExtractionOutput
    | Extend.ProvidedClassifierOutput
    | Extend.ProvidedSplitterOutput;
