/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export type ProvidedExtractionOutput = Extend.ProvidedJsonSchema | Extend.ProvidedExtractionOutputLegacy;
