// This file was auto-generated by Fern from our API Definition.

export interface ProvidedSplitOutputSplitsItem {
    /** ID of the classification type (defined in the splitter config) */
    classificationId: string;
    /** The type of the split document (defined in the splitter config), corresponds to the classificationId */
    type: string;
    /** The start page of the split document */
    startPage: number;
    /** The end page of the split document */
    endPage: number;
}
