/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * A mapping of field names to their extracted values
 */
export type ProvidedExtractionOutputLegacy = Record<string, Extend.ProvidedExtractionOutputValue>;
