// This file was auto-generated by Fern from our API Definition.

/**
 * An optional object containing secrets to be used by processors within the workflow for this specific run.
 */
export type RunSecrets = Record<string, unknown>;
