/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Signature {
    /** The printed name associated with the signature */
    printedName: string;
    /** The date of the signature */
    signatureDate: string;
    /** Whether the document is signed */
    isSigned: boolean;
    /** The title or role of the signer */
    titleOrRole: string;
}
