/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Sort in ascending or descending order. Ascending order means the earliest result is returned first.
 */
export type SortDir = "asc" | "desc";
export const SortDir = {
    Asc: "asc",
    Desc: "desc",
} as const;
