// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../index";

/**
 * Summary representation of a split run.
 */
export interface SplitRunSummary {
    /** The type of object. Will always be `"split_run"`. */
    object: "split_run";
    /** The unique identifier for this split run. */
    id: string;
    /**
     * The splitter that was used for this run.
     *
     * **Availability:** Present when a splitter reference was provided. Not present when using inline `config`.
     */
    splitter: Extend.SplitterSummary | null;
    /**
     * The version of the splitter that was used for this run.
     *
     * **Availability:** Present when a splitter reference was provided. Not present when using inline `config`.
     */
    splitterVersion: Extend.SplitterVersionSummary | null;
    status: Extend.ProcessorRunStatus;
    /**
     * The reason for failure.
     *
     * **Availability:** Present when `status` is `"FAILED"`.
     */
    failureReason: string | null;
    /**
     * A detailed message about the failure.
     *
     * **Availability:** Present when `status` is `"FAILED"`.
     */
    failureMessage: string | null;
    /**
     * Any metadata that was provided when creating the split run.
     *
     * **Availability:** Present when metadata was provided during creation.
     */
    metadata: Extend.RunMetadata | null;
    /** Indicates whether the run has been reviewed by a human. */
    reviewed: boolean;
    /** Indicates whether the run results have been edited during review. */
    edited: boolean;
    /** The file that was processed. */
    file: Extend.FileSummary;
    /**
     * The ID of the parse run that was used for this split run.
     *
     * **Availability:** Present when a parse run was created.
     */
    parseRunId: string | null;
    /** The URL to view the split run in the Extend dashboard. */
    dashboardUrl: string;
    /**
     * Usage credits consumed by this run.
     *
     * **Availability:** Present when `status` is `"PROCESSED"`.
     */
    usage: Extend.RunUsage | null;
    createdAt: Extend.CreatedAt;
    updatedAt: Extend.UpdatedAt;
}
