// This file was auto-generated by Fern from our API Definition.

/**
 * A reference to a splitter.
 */
export interface SplitterRef {
    /** The splitter ID. */
    id: string;
    /** The splitter version to use: `"draft"` or a specific semver string (e.g. `"0.1"`). `"latest"` is not allowed because classification IDs used for routing are tied to a specific version's config. */
    version: string;
}
