// This file was auto-generated by Fern from our API Definition.

/**
 * A classification for document splitting. Extends the base Classification with an optional `identifierKey` field for per-type identifier extraction rules.
 */
export interface SplitClassification {
    /** Unique identifier for the classification. We recommend lowercase, underscore-separated format. */
    id: string;
    /** Type identifier for the classification. */
    type: string;
    /** A detailed description of the classification. */
    description: string;
    /**
     * A natural-language rule describing how to extract a unique identifier for subdocuments of this type. For example, `"Extract the invoice number from the document header"`.
     *
     * When provided, the splitter will extract the specified identifier for each subdocument of this type and include it in the output as the `identifier` field. This enables merging of related subdocuments that share the same extracted identifier.
     *
     * **Availability:** Supported on `splitting_light` >= 1.3.0 and `splitting_performance` >= 1.5.0. If provided on older versions, this field is accepted but ignored.
     */
    identifierKey?: string;
}
