/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * The output of the WorkflowStepRun. The shape of the output depends on the type of the WorkflowStep in the `step` field:
 * * For `"EXTERNAL_DATA_VALIDATION"` steps - The output will be the same object that was returned by the external endpoint configured for this step
 * * For `"RULE_VALIDATION"` steps - See the below shape:
 */
export interface StepRunOutput {
    rules?: Extend.StepRunOutputRulesItem[];
}
