/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

/**
 * Webhook event for processor run related events
 */
export interface WebhookEventProcessorRun {
    eventType?: Extend.WebhookEventProcessorRunEventType;
    payload?: Extend.ProcessorRun;
    /** Unique identifier for the event */
    eventId: string;
}
