// This file was auto-generated by Fern from our API Definition.

/** The type of resource the webhook subscription is for. */
export const WebhookSubscriptionResourceType = {
    Extractor: "extractor",
    Classifier: "classifier",
    Splitter: "splitter",
    Workflow: "workflow",
} as const;
export type WebhookSubscriptionResourceType =
    | (typeof WebhookSubscriptionResourceType)[keyof typeof WebhookSubscriptionResourceType]
    | string;
