// This file was auto-generated by Fern from our API Definition.

/**
 * A terminal step that triggers webhook delivery of the workflow results.
 *
 * See the [Webhook Response step docs](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#webhook-response-step).
 */
export interface WebhookResponseStepDefinition {
    name: string;
}
