/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../index";

export interface WorkflowRunCancelledWebhookEvent {
    /** Unique identifier for the event */
    eventId: string;
    payload: Extend.WorkflowRun;
}
