// This file was auto-generated by Fern from our API Definition.

export interface Workflow {
    /** The type of object. In this case, it will always be `"workflow"`. */
    object: "workflow";
    /**
     * The ID of the workflow.
     *
     * Example: `"workflow_BMlfq_yWM3sT-ZzvCnA3f"`
     */
    id: string;
    /**
     * The name of the workflow.
     *
     * Example: `"Invoice Processing"`
     */
    name: string;
}
