// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../index";

export interface ParseRunsCreateBatchRequestInputsItem {
    /** The file to parse. Can be a URL, an Extend file ID, or raw text. */
    file: Extend.ParseRunsCreateBatchRequestInputsItemFile;
    metadata?: Extend.RunMetadata;
}
