// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../index";

export interface ParseRunsListResponse {
    object: "list";
    data: Extend.ParseRun[];
    nextPageToken?: Extend.NextPageToken;
}
