// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../index";

/**
 * @example
 *     {
 *         config: {
 *             schema: {
 *                 "type": "object",
 *                 "properties": {
 *                     "vendor_name": {
 *                         "type": "string",
 *                         "description": "The name of the vendor"
 *                     },
 *                     "invoice_number": {
 *                         "type": "string",
 *                         "description": "The invoice number"
 *                     },
 *                     "total_amount": {
 *                         "type": "number",
 *                         "description": "The total amount due"
 *                     }
 *                 }
 *             }
 *         },
 *         file: {
 *             url: "https://example.com/invoice.pdf"
 *         }
 *     }
 */
export interface ExtractRequest {
    /** Reference to an existing extractor. One of `extractor` or `config` must be provided. */
    extractor?: Extend.ExtractRequestExtractor;
    /** Inline extract configuration. One of `extractor` or `config` must be provided. */
    config?: Extend.ExtractConfigJson;
    /** The file to be extracted from. Files can be provided as a URL, Extend file ID, or raw text. */
    file: Extend.ExtractRequestFile;
    metadata?: Extend.RunMetadata;
}
