/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../index";

/**
 * @example
 *     {
 *         responseType: "json",
 *         file: {}
 *     }
 */
export interface ParseRequest {
    /**
     * Controls the format of the response chunks. Defaults to `json` if not specified.
     * * `json` - Returns parsed outputs in the response body
     * * `url` - Return a presigned URL to the parsed content in the response body
     */
    responseType?: Extend.ParseRequestResponseType;
    /** The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2025-04-21/developers/authentication) for details on API key scopes. */
    "x-extend-workspace-id"?: string;
    /** A file object containing either a URL or a fileId. */
    file: Extend.ParseRequestFile;
    config?: Extend.ParseConfig;
}
