/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Extend from "../../../../api/index";
import * as core from "../../../../core";
import { WorkflowRun } from "../../../types/WorkflowRun";

export const WorkflowRunCreateResponse: core.serialization.ObjectSchema<
    serializers.WorkflowRunCreateResponse.Raw,
    Extend.WorkflowRunCreateResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    workflowRuns: core.serialization.list(WorkflowRun),
});

export declare namespace WorkflowRunCreateResponse {
    export interface Raw {
        success: boolean;
        workflowRuns: WorkflowRun.Raw[];
    }
}
