/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Extend from "../../../../api/index";
import * as core from "../../../../core";
import { WorkflowRunSummary } from "../../../types/WorkflowRunSummary";
import { NextPageToken } from "../../../types/NextPageToken";

export const WorkflowRunListResponse: core.serialization.ObjectSchema<
    serializers.WorkflowRunListResponse.Raw,
    Extend.WorkflowRunListResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    workflowRuns: core.serialization.list(WorkflowRunSummary),
    nextPageToken: NextPageToken.optional(),
});

export declare namespace WorkflowRunListResponse {
    export interface Raw {
        success: boolean;
        workflowRuns: WorkflowRunSummary.Raw[];
        nextPageToken?: NextPageToken.Raw | null;
    }
}
