/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const BatchProcessorRunStatus: core.serialization.Schema<
    serializers.BatchProcessorRunStatus.Raw,
    Extend.BatchProcessorRunStatus
> = core.serialization.enum_(["PENDING", "PROCESSING", "PROCESSED", "FAILED"]);

export declare namespace BatchProcessorRunStatus {
    export type Raw = "PENDING" | "PROCESSING" | "PROCESSED" | "FAILED";
}
