/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const BlockBoundingBox: core.serialization.ObjectSchema<
    serializers.BlockBoundingBox.Raw,
    Extend.BlockBoundingBox
> = core.serialization.object({
    left: core.serialization.number().optional(),
    right: core.serialization.number().optional(),
    top: core.serialization.number().optional(),
    bottom: core.serialization.number().optional(),
});

export declare namespace BlockBoundingBox {
    export interface Raw {
        left?: number | null;
        right?: number | null;
        top?: number | null;
        bottom?: number | null;
    }
}
