/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";
import { ChunkType } from "./ChunkType";
import { ChunkMetadata } from "./ChunkMetadata";
import { Block } from "./Block";

export const Chunk: core.serialization.ObjectSchema<serializers.Chunk.Raw, Extend.Chunk> = core.serialization.object({
    object: core.serialization.string(),
    type: ChunkType,
    content: core.serialization.string(),
    metadata: ChunkMetadata,
    blocks: core.serialization.list(Block),
});

export declare namespace Chunk {
    export interface Raw {
        object: string;
        type: ChunkType.Raw;
        content: string;
        metadata: ChunkMetadata.Raw;
        blocks: Block.Raw[];
    }
}
