/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";
import { Insight } from "./Insight";

export const ClassifierOutput: core.serialization.ObjectSchema<
    serializers.ClassifierOutput.Raw,
    Extend.ClassifierOutput
> = core.serialization.object({
    id: core.serialization.string(),
    type: core.serialization.string(),
    confidence: core.serialization.number(),
    insights: core.serialization.list(Insight),
});

export declare namespace ClassifierOutput {
    export interface Raw {
        id: string;
        type: string;
        confidence: number;
        insights: Insight.Raw[];
    }
}
