/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const ClassificationConfigBaseProcessor: core.serialization.Schema<
    serializers.ClassificationConfigBaseProcessor.Raw,
    Extend.ClassificationConfigBaseProcessor
> = core.serialization.enum_(["classifier_performance", "classifier_light"]);

export declare namespace ClassificationConfigBaseProcessor {
    export type Raw = "classifier_performance" | "classifier_light";
}
