/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const EnumOption: core.serialization.ObjectSchema<serializers.EnumOption.Raw, Extend.EnumOption> =
    core.serialization.object({
        value: core.serialization.string(),
        description: core.serialization.string(),
    });

export declare namespace EnumOption {
    export interface Raw {
        value: string;
        description: string;
    }
}
