/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, Extend.Error_> = core.serialization.object(
    {
        success: core.serialization.boolean().optional(),
        error: core.serialization.string().optional(),
    },
);

export declare namespace Error_ {
    export interface Raw {
        success?: boolean | null;
        error?: string | null;
    }
}
