/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const ExtractionFieldType: core.serialization.Schema<
    serializers.ExtractionFieldType.Raw,
    Extend.ExtractionFieldType
> = core.serialization.enum_([
    "string",
    "number",
    "currency",
    "boolean",
    "date",
    "array",
    "enum",
    "object",
    "signature",
]);

export declare namespace ExtractionFieldType {
    export type Raw = "string" | "number" | "currency" | "boolean" | "date" | "array" | "enum" | "object" | "signature";
}
