/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";
import { ExtractChunkingOptions } from "./ExtractChunkingOptions";

export const ExtractionAdvancedOptions: core.serialization.ObjectSchema<
    serializers.ExtractionAdvancedOptions.Raw,
    Extend.ExtractionAdvancedOptions
> = core.serialization.object({
    documentKind: core.serialization.string().optional(),
    keyDefinitions: core.serialization.string().optional(),
    modelReasoningInsightsEnabled: core.serialization.boolean().optional(),
    advancedMultimodalEnabled: core.serialization.boolean().optional(),
    citationsEnabled: core.serialization.boolean().optional(),
    autoReviewAssistantEnabled: core.serialization.boolean().optional(),
    advancedFigureParsingEnabled: core.serialization.boolean().optional(),
    chunkingOptions: ExtractChunkingOptions.optional(),
    fixedPageLimit: core.serialization.number().optional(),
});

export declare namespace ExtractionAdvancedOptions {
    export interface Raw {
        documentKind?: string | null;
        keyDefinitions?: string | null;
        modelReasoningInsightsEnabled?: boolean | null;
        advancedMultimodalEnabled?: boolean | null;
        citationsEnabled?: boolean | null;
        autoReviewAssistantEnabled?: boolean | null;
        advancedFigureParsingEnabled?: boolean | null;
        chunkingOptions?: ExtractChunkingOptions.Raw | null;
        fixedPageLimit?: number | null;
    }
}
