/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const ExtractionFieldResultType: core.serialization.Schema<
    serializers.ExtractionFieldResultType.Raw,
    Extend.ExtractionFieldResultType
> = core.serialization.enum_([
    "string",
    "number",
    "currency",
    "boolean",
    "date",
    "enum",
    "array",
    "object",
    "signature",
]);

export declare namespace ExtractionFieldResultType {
    export type Raw = "string" | "number" | "currency" | "boolean" | "date" | "enum" | "array" | "object" | "signature";
}
