/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const FileType: core.serialization.Schema<serializers.FileType.Raw, Extend.FileType> = core.serialization.enum_([
    "PDF",
    "CSV",
    "IMG",
    "TXT",
    "DOCX",
    "EXCEL",
    "XML",
    "HTML",
]);

export declare namespace FileType {
    export type Raw = "PDF" | "CSV" | "IMG" | "TXT" | "DOCX" | "EXCEL" | "XML" | "HTML";
}
