/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const JsonOutputMetadataValueCitationsItemPolygonItem: core.serialization.ObjectSchema<
    serializers.JsonOutputMetadataValueCitationsItemPolygonItem.Raw,
    Extend.JsonOutputMetadataValueCitationsItemPolygonItem
> = core.serialization.object({
    x: core.serialization.number(),
    y: core.serialization.number(),
});

export declare namespace JsonOutputMetadataValueCitationsItemPolygonItem {
    export interface Raw {
        x: number;
        y: number;
    }
}
