/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const JsonObject: core.serialization.Schema<serializers.JsonObject.Raw, Extend.JsonObject> =
    core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace JsonObject {
    export type Raw = Record<string, unknown>;
}
