/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const ParseConfigAdvancedOptions: core.serialization.ObjectSchema<
    serializers.ParseConfigAdvancedOptions.Raw,
    Extend.ParseConfigAdvancedOptions
> = core.serialization.object({
    pageRotationEnabled: core.serialization.boolean().optional(),
});

export declare namespace ParseConfigAdvancedOptions {
    export interface Raw {
        pageRotationEnabled?: boolean | null;
    }
}
