/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";
import { ParseErrorCode } from "./ParseErrorCode";

export const ParseError: core.serialization.ObjectSchema<serializers.ParseError.Raw, Extend.ParseError> =
    core.serialization.object({
        code: ParseErrorCode.optional(),
        message: core.serialization.string().optional(),
        requestId: core.serialization.string().optional(),
        retryable: core.serialization.boolean().optional(),
    });

export declare namespace ParseError {
    export interface Raw {
        code?: ParseErrorCode.Raw | null;
        message?: string | null;
        requestId?: string | null;
        retryable?: boolean | null;
    }
}
