/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const Polygon: core.serialization.ObjectSchema<serializers.Polygon.Raw, Extend.Polygon> =
    core.serialization.object({
        x: core.serialization.number(),
        y: core.serialization.number(),
    });

export declare namespace Polygon {
    export interface Raw {
        x: number;
        y: number;
    }
}
