/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const ProcessorRunStatus: core.serialization.Schema<
    serializers.ProcessorRunStatus.Raw,
    Extend.ProcessorRunStatus
> = core.serialization.enum_(["PROCESSING", "PROCESSED", "FAILED"]);

export declare namespace ProcessorRunStatus {
    export type Raw = "PROCESSING" | "PROCESSED" | "FAILED";
}
