/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const ProcessorRunFileInput: core.serialization.ObjectSchema<
    serializers.ProcessorRunFileInput.Raw,
    Extend.ProcessorRunFileInput
> = core.serialization.object({
    fileName: core.serialization.string().optional(),
    fileUrl: core.serialization.string().optional(),
    fileId: core.serialization.string().optional(),
});

export declare namespace ProcessorRunFileInput {
    export interface Raw {
        fileName?: string | null;
        fileUrl?: string | null;
        fileId?: string | null;
    }
}
