/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const SplitterOutputSplitsItem: core.serialization.ObjectSchema<
    serializers.SplitterOutputSplitsItem.Raw,
    Extend.SplitterOutputSplitsItem
> = core.serialization.object({
    type: core.serialization.string(),
    observation: core.serialization.string(),
    identifier: core.serialization.string(),
    name: core.serialization.string().optional(),
});

export declare namespace SplitterOutputSplitsItem {
    export interface Raw {
        type: string;
        observation: string;
        identifier: string;
        name?: string | null;
    }
}
