/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";
import { SplitterOutputSplitsItem } from "./SplitterOutputSplitsItem";

export const SplitterOutput: core.serialization.ObjectSchema<serializers.SplitterOutput.Raw, Extend.SplitterOutput> =
    core.serialization.object({
        splits: core.serialization.list(SplitterOutputSplitsItem),
        isExternal: core.serialization.boolean().optional(),
    });

export declare namespace SplitterOutput {
    export interface Raw {
        splits: SplitterOutputSplitsItem.Raw[];
        isExternal?: boolean | null;
    }
}
