/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";

export const SplitterAdvancedOptionsSplitMethod: core.serialization.Schema<
    serializers.SplitterAdvancedOptionsSplitMethod.Raw,
    Extend.SplitterAdvancedOptionsSplitMethod
> = core.serialization.enum_(["high_precision", "low_latency"]);

export declare namespace SplitterAdvancedOptionsSplitMethod {
    export type Raw = "high_precision" | "low_latency";
}
