/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";
import { ProcessorVersion } from "./ProcessorVersion";

export const WebhookEventProcessorVersion: core.serialization.ObjectSchema<
    serializers.WebhookEventProcessorVersion.Raw,
    Extend.WebhookEventProcessorVersion
> = core.serialization.object({
    eventType: core.serialization.stringLiteral("processor.version.published").optional(),
    payload: ProcessorVersion.optional(),
    eventId: core.serialization.string(),
});

export declare namespace WebhookEventProcessorVersion {
    export interface Raw {
        eventType?: "processor.version.published" | null;
        payload?: ProcessorVersion.Raw | null;
        eventId: string;
    }
}
