/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Extend from "../../api/index";
import * as core from "../../core";
import { ProvidedProcessorOutput } from "./ProvidedProcessorOutput";

export const WorkflowRunFileInputOutputsItem: core.serialization.ObjectSchema<
    serializers.WorkflowRunFileInputOutputsItem.Raw,
    Extend.WorkflowRunFileInputOutputsItem
> = core.serialization.object({
    processorId: core.serialization.string(),
    output: ProvidedProcessorOutput,
});

export declare namespace WorkflowRunFileInputOutputsItem {
    export interface Raw {
        processorId: string;
        output: ProvidedProcessorOutput.Raw;
    }
}
