/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Extend from "../../../../../api/index";
import * as core from "../../../../../core";
import { WorkflowRunFileInput } from "../../../../types/WorkflowRunFileInput";
import { JsonObject } from "../../../../types/JsonObject";

export const WorkflowRunCreateRequest: core.serialization.Schema<
    serializers.WorkflowRunCreateRequest.Raw,
    Extend.WorkflowRunCreateRequest
> = core.serialization.object({
    workflowId: core.serialization.string(),
    files: core.serialization.list(WorkflowRunFileInput).optional(),
    rawTexts: core.serialization.list(core.serialization.string()).optional(),
    version: core.serialization.string().optional(),
    priority: core.serialization.number().optional(),
    metadata: JsonObject.optional(),
});

export declare namespace WorkflowRunCreateRequest {
    export interface Raw {
        workflowId: string;
        files?: WorkflowRunFileInput.Raw[] | null;
        rawTexts?: string[] | null;
        version?: string | null;
        priority?: number | null;
        metadata?: JsonObject.Raw | null;
    }
}
