// This file was auto-generated by Fern from our API Definition.

export const ProcessorListRequestSortDir = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ProcessorListRequestSortDir =
    | (typeof ProcessorListRequestSortDir)[keyof typeof ProcessorListRequestSortDir]
    | string;
