/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Extend from "../../../../api/index";
import * as core from "../../../../core";
import { ProcessorRun } from "../../../types/ProcessorRun";

export const ProcessorRunCreateResponse: core.serialization.ObjectSchema<
    serializers.ProcessorRunCreateResponse.Raw,
    Extend.ProcessorRunCreateResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    processorRun: ProcessorRun,
});

export declare namespace ProcessorRunCreateResponse {
    export interface Raw {
        success: boolean;
        processorRun: ProcessorRun.Raw;
    }
}
