// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         nextPageToken: "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="
 *     }
 */
export interface FilesListRequest {
    /**
     * Filters files to only include those that contain the given string in the name.
     *
     * Example: `"invoice"`
     */
    nameContains?: string;
    sortDir?: Extend.SortDir;
    nextPageToken?: Extend.NextPageToken;
    maxPageSize?: Extend.MaxPageSize;
}
