// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../index";

/**
 * Reference to the splitter to run against every input in this batch.
 */
export interface SplitRunsCreateBatchRequestSplitter {
    /** The ID of the splitter to use. */
    id: string;
    version?: Extend.ProcessorVersionString;
    /** Optional partial configuration override applied to every run in this batch. Only the fields you provide will override the splitter's saved configuration. */
    overrideConfig?: Extend.SplitOverrideConfig;
}
