// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../index";

/**
 * Reference to an existing splitter. One of `splitter` or `config` must be provided.
 */
export interface SplitRunsCreateRequestSplitter {
    /** The ID of the splitter to use. */
    id: string;
    version?: Extend.ProcessorVersionString;
    /** Optional configuration override. If provided, this configuration will override the splitter's saved configuration. */
    overrideConfig?: Extend.SplitConfig;
}
