/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../index";

export interface SplitRunsListResponse {
    splitRuns: Extend.SplitRunSummary[];
    nextPageToken?: Extend.NextPageToken;
}
