// This file was auto-generated by Fern from our API Definition.

import * as Extend from "../../src/api/index";
import { ExtendClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EditRunsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = {
            object: "edit_run",
            id: "edr_xK9mLPqRtN3vS8wF5hB2cQ",
            file: {
                object: "file",
                id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                name: "Invoices.pdf",
                type: "PDF",
                parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                metadata: {
                    pageCount: 30,
                    parentSplit: { id: "id", type: "Invoice", identifier: "other_2_9", startPage: 1, endPage: 10 },
                },
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
            },
            status: "PROCESSING",
            failureReason: "FILE_TYPE_NOT_SUPPORTED",
            failureMessage: "File type not supported. Edit runs currently require a PDF.",
            config: {
                schema: { type: "object", properties: { key: {} }, required: ["required"], additionalProperties: true },
                instructions: "instructions",
                advancedOptions: { tableParsingEnabled: true, flattenPdf: true },
            },
            output: {
                editedFile: {
                    id: "file_Ab3cDE45Fg6hIj7KlM8nO",
                    presignedUrl: "https://extend-ai-files.s3.amazonaws.com/...",
                },
                filledValues: { key: "value" },
            },
            metrics: {
                processingTimeMs: 1234,
                pageCount: 5,
                fieldCount: 10,
                fieldsDetectedCount: 8,
                fieldsAnnotatedCount: 10,
                fieldDetectionTimeMs: 500,
                fieldAnnotationTimeMs: 200,
                fieldFillingTimeMs: 300,
            },
            usage: { credits: 10 },
        };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.editRuns.create({
            file: {
                url: "url",
            },
        });
        expect(response).toEqual({
            object: "edit_run",
            id: "edr_xK9mLPqRtN3vS8wF5hB2cQ",
            file: {
                object: "file",
                id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                name: "Invoices.pdf",
                type: "PDF",
                parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                metadata: {
                    pageCount: 30,
                    parentSplit: {
                        id: "id",
                        type: "Invoice",
                        identifier: "other_2_9",
                        startPage: 1,
                        endPage: 10,
                    },
                },
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
            },
            status: "PROCESSING",
            failureReason: "FILE_TYPE_NOT_SUPPORTED",
            failureMessage: "File type not supported. Edit runs currently require a PDF.",
            config: {
                schema: {
                    type: "object",
                    properties: {
                        key: {},
                    },
                    required: ["required"],
                    additionalProperties: true,
                },
                instructions: "instructions",
                advancedOptions: {
                    tableParsingEnabled: true,
                    flattenPdf: true,
                },
            },
            output: {
                editedFile: {
                    id: "file_Ab3cDE45Fg6hIj7KlM8nO",
                    presignedUrl: "https://extend-ai-files.s3.amazonaws.com/...",
                },
                filledValues: {
                    key: "value",
                },
            },
            metrics: {
                processingTimeMs: 1234,
                pageCount: 5,
                fieldCount: 10,
                fieldsDetectedCount: 8,
                fieldsAnnotatedCount: 10,
                fieldDetectionTimeMs: 500,
                fieldAnnotationTimeMs: 200,
                fieldFillingTimeMs: 300,
            },
            usage: {
                credits: 10,
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.editRuns.create({
                file: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.editRuns.create({
                file: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.editRuns.create({
                file: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.editRuns.create({
                file: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.editRuns.create({
                file: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.editRuns.create({
                file: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.editRuns.create({
                file: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { file: { url: "url" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/edit_runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.editRuns.create({
                file: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Extend.InternalServerError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            object: "edit_run",
            id: "edr_xK9mLPqRtN3vS8wF5hB2cQ",
            file: {
                object: "file",
                id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                name: "Invoices.pdf",
                type: "PDF",
                parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                metadata: {
                    pageCount: 30,
                    parentSplit: { id: "id", type: "Invoice", identifier: "other_2_9", startPage: 1, endPage: 10 },
                },
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
            },
            status: "PROCESSING",
            failureReason: "FILE_TYPE_NOT_SUPPORTED",
            failureMessage: "File type not supported. Edit runs currently require a PDF.",
            config: {
                schema: { type: "object", properties: { key: {} }, required: ["required"], additionalProperties: true },
                instructions: "instructions",
                advancedOptions: { tableParsingEnabled: true, flattenPdf: true },
            },
            output: {
                editedFile: {
                    id: "file_Ab3cDE45Fg6hIj7KlM8nO",
                    presignedUrl: "https://extend-ai-files.s3.amazonaws.com/...",
                },
                filledValues: { key: "value" },
            },
            metrics: {
                processingTimeMs: 1234,
                pageCount: 5,
                fieldCount: 10,
                fieldsDetectedCount: 8,
                fieldsAnnotatedCount: 10,
                fieldDetectionTimeMs: 500,
                fieldAnnotationTimeMs: 200,
                fieldFillingTimeMs: 300,
            },
            usage: { credits: 10 },
        };
        server
            .mockEndpoint()
            .get("/edit_runs/edit_run_id_here")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.editRuns.retrieve("edit_run_id_here");
        expect(response).toEqual({
            object: "edit_run",
            id: "edr_xK9mLPqRtN3vS8wF5hB2cQ",
            file: {
                object: "file",
                id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                name: "Invoices.pdf",
                type: "PDF",
                parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                metadata: {
                    pageCount: 30,
                    parentSplit: {
                        id: "id",
                        type: "Invoice",
                        identifier: "other_2_9",
                        startPage: 1,
                        endPage: 10,
                    },
                },
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
            },
            status: "PROCESSING",
            failureReason: "FILE_TYPE_NOT_SUPPORTED",
            failureMessage: "File type not supported. Edit runs currently require a PDF.",
            config: {
                schema: {
                    type: "object",
                    properties: {
                        key: {},
                    },
                    required: ["required"],
                    additionalProperties: true,
                },
                instructions: "instructions",
                advancedOptions: {
                    tableParsingEnabled: true,
                    flattenPdf: true,
                },
            },
            output: {
                editedFile: {
                    id: "file_Ab3cDE45Fg6hIj7KlM8nO",
                    presignedUrl: "https://extend-ai-files.s3.amazonaws.com/...",
                },
                filledValues: {
                    key: "value",
                },
            },
            metrics: {
                processingTimeMs: 1234,
                pageCount: 5,
                fieldCount: 10,
                fieldsDetectedCount: 8,
                fieldsAnnotatedCount: 10,
                fieldDetectionTimeMs: 500,
                fieldAnnotationTimeMs: 200,
                fieldFillingTimeMs: 300,
            },
            usage: {
                credits: 10,
            },
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_runs/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.retrieve("id");
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_runs/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.retrieve("id");
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().get("/edit_runs/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.retrieve("id");
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().get("/edit_runs/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.retrieve("id");
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_runs/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.retrieve("id");
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("retrieve (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().get("/edit_runs/id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.retrieve("id");
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("retrieve (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_runs/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.retrieve("id");
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("retrieve (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_runs/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.retrieve("id");
        }).rejects.toThrow(Extend.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { id: "edr_xK9mLPqRtN3vS8wF5hB2cQ" };
        server
            .mockEndpoint()
            .delete("/edit_runs/edit_run_id_here")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.editRuns.delete("edit_run_id_here");
        expect(response).toEqual({
            id: "edr_xK9mLPqRtN3vS8wF5hB2cQ",
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/edit_runs/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.delete("id");
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/edit_runs/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.delete("id");
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().delete("/edit_runs/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.delete("id");
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().delete("/edit_runs/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.delete("id");
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/edit_runs/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.delete("id");
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("delete (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().delete("/edit_runs/id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.delete("id");
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("delete (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/edit_runs/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.delete("id");
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("delete (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/edit_runs/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editRuns.delete("id");
        }).rejects.toThrow(Extend.InternalServerError);
    });
});
