// This file was auto-generated by Fern from our API Definition.

import * as Extend from "../../src/api/index";
import { ExtendClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EditTemplatesClient", () => {
    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            object: "edit_template",
            id: "edt_xK9mLPqRtN3vS8wF5hB2cQ",
            name: "W-9 Template",
            description: "Fill a W-9 form",
            file: {
                object: "file",
                id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                name: "Invoices.pdf",
                type: "PDF",
                parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                metadata: {
                    pageCount: 30,
                    parentSplit: { id: "id", type: "Invoice", identifier: "other_2_9", startPage: 1, endPage: 10 },
                },
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
            },
            config: {
                schema: {
                    type: "object",
                    properties: { key: {} },
                    required: ["required"],
                    additionalProperties: true,
                    dependentRequired: { key: ["value"] },
                    allOf: [{}],
                    oneOf: [{}],
                    anyOf: [{}],
                },
                instructions: "instructions",
                schemaGenerationInstructions: "schemaGenerationInstructions",
                advancedOptions: {
                    tableParsingEnabled: true,
                    flattenPdf: true,
                    radioEnumsEnabled: true,
                    nativeFieldsOnly: true,
                    conditionalGenerationEnabled: true,
                },
            },
            schemaConfig: {
                inputSchema: {
                    type: "object",
                    properties: { key: {} },
                    required: ["required"],
                    additionalProperties: true,
                    dependentRequired: { key: ["value"] },
                    allOf: [{}],
                    oneOf: [{}],
                    anyOf: [{}],
                },
                instructions: "instructions",
                advancedOptions: {
                    tableParsingEnabled: true,
                    radioEnumsEnabled: true,
                    nativeFieldsOnly: true,
                    conditionalGenerationEnabled: true,
                },
            },
            createdAt: "2024-03-21T16:45:00Z",
            updatedAt: "2024-03-21T16:45:00Z",
        };
        server
            .mockEndpoint()
            .get("/edit_templates/edit_template_id_here")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.editTemplates.retrieve("edit_template_id_here");
        expect(response).toEqual({
            object: "edit_template",
            id: "edt_xK9mLPqRtN3vS8wF5hB2cQ",
            name: "W-9 Template",
            description: "Fill a W-9 form",
            file: {
                object: "file",
                id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                name: "Invoices.pdf",
                type: "PDF",
                parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                metadata: {
                    pageCount: 30,
                    parentSplit: {
                        id: "id",
                        type: "Invoice",
                        identifier: "other_2_9",
                        startPage: 1,
                        endPage: 10,
                    },
                },
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
            },
            config: {
                schema: {
                    type: "object",
                    properties: {
                        key: {},
                    },
                    required: ["required"],
                    additionalProperties: true,
                    dependentRequired: {
                        key: ["value"],
                    },
                    allOf: [{}],
                    oneOf: [{}],
                    anyOf: [{}],
                },
                instructions: "instructions",
                schemaGenerationInstructions: "schemaGenerationInstructions",
                advancedOptions: {
                    tableParsingEnabled: true,
                    flattenPdf: true,
                    radioEnumsEnabled: true,
                    nativeFieldsOnly: true,
                    conditionalGenerationEnabled: true,
                },
            },
            schemaConfig: {
                inputSchema: {
                    type: "object",
                    properties: {
                        key: {},
                    },
                    required: ["required"],
                    additionalProperties: true,
                    dependentRequired: {
                        key: ["value"],
                    },
                    allOf: [{}],
                    oneOf: [{}],
                    anyOf: [{}],
                },
                instructions: "instructions",
                advancedOptions: {
                    tableParsingEnabled: true,
                    radioEnumsEnabled: true,
                    nativeFieldsOnly: true,
                    conditionalGenerationEnabled: true,
                },
            },
            createdAt: "2024-03-21T16:45:00Z",
            updatedAt: "2024-03-21T16:45:00Z",
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_templates/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editTemplates.retrieve("id");
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_templates/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editTemplates.retrieve("id");
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().get("/edit_templates/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editTemplates.retrieve("id");
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().get("/edit_templates/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editTemplates.retrieve("id");
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_templates/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editTemplates.retrieve("id");
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("retrieve (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server.mockEndpoint().get("/edit_templates/id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editTemplates.retrieve("id");
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("retrieve (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_templates/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editTemplates.retrieve("id");
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("retrieve (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/edit_templates/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.editTemplates.retrieve("id");
        }).rejects.toThrow(Extend.InternalServerError);
    });
});
