/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { ExtendClient } from "../../src/Client";
import * as Extend from "../../src/api/index";

describe("Extractors", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            extractors: [
                {
                    object: "extractor_summary",
                    id: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                    name: "Invoice Extractor",
                    createdAt: "2024-03-21T16:45:00Z",
                    updatedAt: "2024-03-21T16:45:00Z",
                },
            ],
            nextPageToken: "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ=",
        };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.extractors.list({
            nextPageToken: "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ=",
            maxPageSize: 1,
            sortBy: "updatedAt",
            sortDir: "asc",
        });
        expect(response).toEqual({
            extractors: [
                {
                    object: "extractor_summary",
                    id: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                    name: "Invoice Extractor",
                    createdAt: "2024-03-21T16:45:00Z",
                    updatedAt: "2024-03-21T16:45:00Z",
                },
            ],
            nextPageToken: "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ=",
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.list();
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.list();
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.list();
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.list();
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.list();
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.list();
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("list (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.list();
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("list (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.list();
        }).rejects.toThrow(Extend.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            extractor: {
                object: "extractor",
                id: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                name: "Invoice Extractor",
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
                draftVersion: {
                    object: "extractor_version",
                    id: "extractor_vsn_xK9mLPqRtN3vS8wF5hB2cQ",
                    description: "Updated extraction fields for new invoice format",
                    version: "draft",
                    config: { schema: { key: "value" } },
                    extractorId: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                    createdAt: "2024-03-21T16:45:00Z",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.extractors.create({
            name: "name",
        });
        expect(response).toEqual({
            extractor: {
                object: "extractor",
                id: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                name: "Invoice Extractor",
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
                draftVersion: {
                    object: "extractor_version",
                    id: "extractor_vsn_xK9mLPqRtN3vS8wF5hB2cQ",
                    description: "Updated extraction fields for new invoice format",
                    version: "draft",
                    config: {
                        schema: {
                            key: "value",
                        },
                    },
                    extractorId: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                    createdAt: "2024-03-21T16:45:00Z",
                },
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", cloneExtractorId: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.create({
                name: "name",
                cloneExtractorId: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", cloneExtractorId: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.create({
                name: "name",
                cloneExtractorId: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", cloneExtractorId: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.create({
                name: "name",
                cloneExtractorId: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", cloneExtractorId: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.create({
                name: "name",
                cloneExtractorId: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", cloneExtractorId: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.create({
                name: "name",
                cloneExtractorId: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", cloneExtractorId: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.create({
                name: "name",
                cloneExtractorId: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", cloneExtractorId: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.create({
                name: "name",
                cloneExtractorId: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", cloneExtractorId: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.create({
                name: "name",
                cloneExtractorId: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.InternalServerError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            extractor: {
                object: "extractor",
                id: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                name: "Invoice Extractor",
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
                draftVersion: {
                    object: "extractor_version",
                    id: "extractor_vsn_xK9mLPqRtN3vS8wF5hB2cQ",
                    description: "Updated extraction fields for new invoice format",
                    version: "draft",
                    config: { schema: { key: "value" } },
                    extractorId: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                    createdAt: "2024-03-21T16:45:00Z",
                },
            },
        };
        server
            .mockEndpoint()
            .get("/extractors/extractor_id_here")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.extractors.retrieve("extractor_id_here");
        expect(response).toEqual({
            extractor: {
                object: "extractor",
                id: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                name: "Invoice Extractor",
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
                draftVersion: {
                    object: "extractor_version",
                    id: "extractor_vsn_xK9mLPqRtN3vS8wF5hB2cQ",
                    description: "Updated extraction fields for new invoice format",
                    version: "draft",
                    config: {
                        schema: {
                            key: "value",
                        },
                    },
                    extractorId: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                    createdAt: "2024-03-21T16:45:00Z",
                },
            },
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.retrieve("id");
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.retrieve("id");
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.retrieve("id");
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.retrieve("id");
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.retrieve("id");
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("retrieve (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors/id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.retrieve("id");
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("retrieve (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.retrieve("id");
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("retrieve (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/extractors/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.extractors.retrieve("id");
        }).rejects.toThrow(Extend.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            extractor: {
                object: "extractor",
                id: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                name: "Invoice Extractor",
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
                draftVersion: {
                    object: "extractor_version",
                    id: "extractor_vsn_xK9mLPqRtN3vS8wF5hB2cQ",
                    description: "Updated extraction fields for new invoice format",
                    version: "draft",
                    config: { schema: { key: "value" } },
                    extractorId: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                    createdAt: "2024-03-21T16:45:00Z",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/extractors/extractor_id_here")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.extractors.update("extractor_id_here");
        expect(response).toEqual({
            extractor: {
                object: "extractor",
                id: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                name: "Invoice Extractor",
                createdAt: "2024-03-21T16:45:00Z",
                updatedAt: "2024-03-21T16:45:00Z",
                draftVersion: {
                    object: "extractor_version",
                    id: "extractor_vsn_xK9mLPqRtN3vS8wF5hB2cQ",
                    description: "Updated extraction fields for new invoice format",
                    version: "draft",
                    config: {
                        schema: {
                            key: "value",
                        },
                    },
                    extractorId: "extractor_Xj8mK2pL9nR4vT7qY5wZ",
                    createdAt: "2024-03-21T16:45:00Z",
                },
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.update("id", {
                name: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.update("id", {
                name: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.update("id", {
                name: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.update("id", {
                name: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.update("id", {
                name: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.update("id", {
                name: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.update("id", {
                name: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("update (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extractors/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractors.update("id", {
                name: undefined,
                config: undefined,
            });
        }).rejects.toThrow(Extend.InternalServerError);
    });
});
