// This file was auto-generated by Fern from our API Definition.

import * as Extend from "../../src/api/index";
import { ExtendClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WorkflowsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "Invoice Processing" };
        const rawResponseBody = {
            object: "workflow",
            id: "workflow_BMlfq_yWM3sT-ZzvCnA3f",
            name: "Invoice Processing",
        };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.create({
            name: "Invoice Processing",
        });
        expect(response).toEqual({
            object: "workflow",
            id: "workflow_BMlfq_yWM3sT-ZzvCnA3f",
            name: "Invoice Processing",
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflows.create({
                name: "name",
            });
        }).rejects.toThrow(Extend.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflows.create({
                name: "name",
            });
        }).rejects.toThrow(Extend.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflows.create({
                name: "name",
            });
        }).rejects.toThrow(Extend.PaymentRequiredError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflows.create({
                name: "name",
            });
        }).rejects.toThrow(Extend.ForbiddenError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflows.create({
                name: "name",
            });
        }).rejects.toThrow(Extend.NotFoundError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { code: "code", message: "message", retryable: true };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflows.create({
                name: "name",
            });
        }).rejects.toThrow(Extend.UnprocessableEntityError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflows.create({
                name: "name",
            });
        }).rejects.toThrow(Extend.TooManyRequestsError);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/workflows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflows.create({
                name: "name",
            });
        }).rejects.toThrow(Extend.InternalServerError);
    });
});
