/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { ExtendClient } from "../../src/Client";

describe("WorkflowRunOutput", () => {
    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new ExtendClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { reviewedOutput: { value: { key: "value" } } };
        const rawResponseBody = {
            success: true,
            workflowRun: {
                object: "workflow_run",
                id: "workflow_run_xKm9pNv3qWsY_jL2tR5Dh",
                name: "myFirstFile.pdf",
                url: "https://dashboard.extend.ai/workflows/workflow_Bk9mNp2qWs5_xL8vR4tYh?workflowRunId=workflow_run_Zj3nMx7ZPd9f4c2WQ_kAg",
                status: "PENDING",
                metadata: { key: "value" },
                batchId: "batch_7Ws31-F5",
                files: [
                    {
                        object: "file",
                        id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                        name: "Invoices.pdf",
                        presignedUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
                        parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                        metadata: {
                            pageCount: 30,
                            parentSplit: {
                                id: "id",
                                type: "Invoice",
                                identifier: "other_2_9",
                                startPage: 1,
                                endPage: 10,
                            },
                        },
                        createdAt: "2024-03-21T15:30:00Z",
                        updatedAt: "2024-03-21T16:45:00Z",
                    },
                ],
                failureReason: "failureReason",
                failureMessage: "failureMessage",
                initialRunAt: "2025-04-28T17:01:39Z",
                reviewedBy: "jane.doe@example.com",
                reviewed: true,
                rejectionNote: "rejectionNote",
                reviewedAt: "2024-03-21T16:45:00Z",
                startTime: "2024-03-21T15:30:00Z",
                endTime: "2024-03-21T15:35:00Z",
                outputs: [
                    {
                        object: "document_processor_run",
                        id: "dpr_Xj8mK2pL9nR4vT7qY5wZ",
                        processorId: "dp_Xj8mK2pL9nR4vT7qY5wZ",
                        processorVersionId: "dpv_Xj8mK2pL9nR4vT7qY5wZ",
                        processorName: "Invoice Processor",
                        status: "PROCESSING",
                        output: { value: { key: "value" }, metadata: { key: {} } },
                        reviewed: false,
                        edited: false,
                        edits: { key: { notes: "This is a note about the edit.", page: 15, fieldType: "string" } },
                        type: "CLASSIFY",
                        config: {
                            baseVersion: "3.2.0",
                            classifications: [
                                {
                                    id: "my_unique_id",
                                    type: "invoice",
                                    description:
                                        "An invoice is a document that lists the items purchased and the total amount due.",
                                },
                            ],
                            classificationRules:
                                "Rememeber, when it comes to differentiating between invoices and purchase orders, the most important thing to look for is the date of the document.",
                            type: "CLASSIFY",
                        },
                        files: [
                            {
                                object: "file",
                                id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                                name: "Invoices.pdf",
                                presignedUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
                                parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                                metadata: {
                                    pageCount: 30,
                                    parentSplit: {
                                        id: "id",
                                        type: "Invoice",
                                        identifier: "other_2_9",
                                        startPage: 1,
                                        endPage: 10,
                                    },
                                },
                                createdAt: "2024-03-21T15:30:00Z",
                                updatedAt: "2024-03-21T16:45:00Z",
                            },
                        ],
                        mergedProcessors: [
                            {
                                processorId: "dp_Xj8mK2pL9nR4vT7qY5wZ",
                                processorVersionId: "dpv_Xj8mK2pL9nR4vT7qY5wZ",
                                processorName: "Invoice Line Items Processor",
                            },
                        ],
                        url: "https://dashboard.extend.ai/runs/dpr_Xj8mK2pL9nR4vT7qY5wZ",
                    },
                ],
                stepRuns: [
                    {
                        object: "workflow_step_run",
                        id: "workflow_step_run_xK9mLPqRtN3vS8wF5hB2cQ",
                        status: "PENDING",
                        step: {
                            object: "workflow_step",
                            id: "step_xK9mLPqRtN3vS8wF5hB2cQ",
                            name: "Validate Invoice Total",
                            type: "EXTERNAL_DATA_VALIDATION",
                        },
                    },
                ],
                workflow: {
                    object: "workflow",
                    id: "workflow_BMlfq_yWM3sT-ZzvCnA3f",
                    version: "draft",
                    name: "Invoice Processing",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/workflow_runs/workflow_run_id_here/outputs/output_id_here")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflowRunOutput.update("workflow_run_id_here", "output_id_here", {
            reviewedOutput: {
                value: {
                    key: "value",
                },
            },
        });
        expect(response).toEqual({
            success: true,
            workflowRun: {
                object: "workflow_run",
                id: "workflow_run_xKm9pNv3qWsY_jL2tR5Dh",
                name: "myFirstFile.pdf",
                url: "https://dashboard.extend.ai/workflows/workflow_Bk9mNp2qWs5_xL8vR4tYh?workflowRunId=workflow_run_Zj3nMx7ZPd9f4c2WQ_kAg",
                status: "PENDING",
                metadata: {
                    key: "value",
                },
                batchId: "batch_7Ws31-F5",
                files: [
                    {
                        object: "file",
                        id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                        name: "Invoices.pdf",
                        presignedUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
                        parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                        metadata: {
                            pageCount: 30,
                            parentSplit: {
                                id: "id",
                                type: "Invoice",
                                identifier: "other_2_9",
                                startPage: 1,
                                endPage: 10,
                            },
                        },
                        createdAt: "2024-03-21T15:30:00Z",
                        updatedAt: "2024-03-21T16:45:00Z",
                    },
                ],
                failureReason: "failureReason",
                failureMessage: "failureMessage",
                initialRunAt: "2025-04-28T17:01:39Z",
                reviewedBy: "jane.doe@example.com",
                reviewed: true,
                rejectionNote: "rejectionNote",
                reviewedAt: "2024-03-21T16:45:00Z",
                startTime: "2024-03-21T15:30:00Z",
                endTime: "2024-03-21T15:35:00Z",
                outputs: [
                    {
                        object: "document_processor_run",
                        id: "dpr_Xj8mK2pL9nR4vT7qY5wZ",
                        processorId: "dp_Xj8mK2pL9nR4vT7qY5wZ",
                        processorVersionId: "dpv_Xj8mK2pL9nR4vT7qY5wZ",
                        processorName: "Invoice Processor",
                        status: "PROCESSING",
                        output: {
                            value: {
                                key: "value",
                            },
                            metadata: {
                                key: {},
                            },
                        },
                        reviewed: false,
                        edited: false,
                        edits: {
                            key: {
                                notes: "This is a note about the edit.",
                                page: 15,
                                fieldType: "string",
                            },
                        },
                        type: "CLASSIFY",
                        config: {
                            type: "CLASSIFY",
                            baseVersion: "3.2.0",
                            classifications: [
                                {
                                    id: "my_unique_id",
                                    type: "invoice",
                                    description:
                                        "An invoice is a document that lists the items purchased and the total amount due.",
                                },
                            ],
                            classificationRules:
                                "Rememeber, when it comes to differentiating between invoices and purchase orders, the most important thing to look for is the date of the document.",
                        },
                        files: [
                            {
                                object: "file",
                                id: "file_xK9mLPqRtN3vS8wF5hB2cQ",
                                name: "Invoices.pdf",
                                presignedUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
                                parentFileId: "file_Zk9mNP12Qw4yTv8BdR3H",
                                metadata: {
                                    pageCount: 30,
                                    parentSplit: {
                                        id: "id",
                                        type: "Invoice",
                                        identifier: "other_2_9",
                                        startPage: 1,
                                        endPage: 10,
                                    },
                                },
                                createdAt: "2024-03-21T15:30:00Z",
                                updatedAt: "2024-03-21T16:45:00Z",
                            },
                        ],
                        mergedProcessors: [
                            {
                                processorId: "dp_Xj8mK2pL9nR4vT7qY5wZ",
                                processorVersionId: "dpv_Xj8mK2pL9nR4vT7qY5wZ",
                                processorName: "Invoice Line Items Processor",
                            },
                        ],
                        url: "https://dashboard.extend.ai/runs/dpr_Xj8mK2pL9nR4vT7qY5wZ",
                    },
                ],
                stepRuns: [
                    {
                        object: "workflow_step_run",
                        id: "workflow_step_run_xK9mLPqRtN3vS8wF5hB2cQ",
                        status: "PENDING",
                        step: {
                            object: "workflow_step",
                            id: "step_xK9mLPqRtN3vS8wF5hB2cQ",
                            name: "Validate Invoice Total",
                            type: "EXTERNAL_DATA_VALIDATION",
                        },
                    },
                ],
                workflow: {
                    object: "workflow",
                    id: "workflow_BMlfq_yWM3sT-ZzvCnA3f",
                    version: "draft",
                    name: "Invoice Processing",
                },
            },
        });
    });
});
