/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ExtendEnvironment = {
    Production: "https://api.extend.ai",
} as const;

export type ExtendEnvironment = typeof ExtendEnvironment.Production;
