/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Extend from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostEvaluationSetItemsBulkRequestItemsItem } from "../../types/PostEvaluationSetItemsBulkRequestItemsItem";

export const PostEvaluationSetItemsBulkRequest: core.serialization.Schema<
    serializers.PostEvaluationSetItemsBulkRequest.Raw,
    Extend.PostEvaluationSetItemsBulkRequest
> = core.serialization.object({
    evaluationSetId: core.serialization.string(),
    items: core.serialization.list(PostEvaluationSetItemsBulkRequestItemsItem),
});

export declare namespace PostEvaluationSetItemsBulkRequest {
    export interface Raw {
        evaluationSetId: string;
        items: PostEvaluationSetItemsBulkRequestItemsItem.Raw[];
    }
}
