/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Extend from "../../../index";

export interface GetWorkflowRunsResponse {
    success: boolean;
    workflowRuns: Extend.WorkflowRunSummary[];
    nextPageToken?: Extend.NextPageToken;
}
