// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ClassifiersUpdateRequest {
    /** The new name of the classifier. */
    name?: string;
    /** The new configuration for the classifier. This will update the draft version of the classifier. */
    config?: Extend.ClassifyConfig;
}
