// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {
 *         nextPageToken: "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="
 *     }
 */
export interface ExtractorsListRequest {
    nextPageToken?: Extend.NextPageToken;
    maxPageSize?: Extend.MaxPageSize;
    sortBy?: Extend.SortBy;
    sortDir?: Extend.SortDir;
}
