// This file was auto-generated by Fern from our API Definition.

export const EditRunsListRequestStatus = {
    Processing: "PROCESSING",
    Processed: "PROCESSED",
    Failed: "FAILED",
} as const;
export type EditRunsListRequestStatus =
    | (typeof EditRunsListRequestStatus)[keyof typeof EditRunsListRequestStatus]
    | string;
