// This file was auto-generated by Fern from our API Definition.

import type * as Extend from "../../../../index";

/**
 * @example
 *     {}
 */
export interface SplittersUpdateRequest {
    /** The new name of the splitter. */
    name?: string;
    /** The new configuration for the splitter. This will update the draft version of the splitter. */
    config?: Extend.SplitConfig;
}
